/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Stack API
 * Knowledge Stack backend API for authentication and knowledge management
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AcceptDisclaimerRequest,
  ApiConnectionRequestRequest,
  ApiConnectionRequestResponse,
  ApiConnectionResponse,
  CreateApiConnectionRequest,
  ErrorResponse,
  HTTPValidationError,
  UpdateApiConnectionRequest,
} from '../models/index';
import {
    AcceptDisclaimerRequestFromJSON,
    AcceptDisclaimerRequestToJSON,
    ApiConnectionRequestRequestFromJSON,
    ApiConnectionRequestRequestToJSON,
    ApiConnectionRequestResponseFromJSON,
    ApiConnectionRequestResponseToJSON,
    ApiConnectionResponseFromJSON,
    ApiConnectionResponseToJSON,
    CreateApiConnectionRequestFromJSON,
    CreateApiConnectionRequestToJSON,
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    UpdateApiConnectionRequestFromJSON,
    UpdateApiConnectionRequestToJSON,
} from '../models/index';

export interface AcceptApiConnectionDisclaimerRequest {
    connectionId: string;
    acceptDisclaimerRequest: AcceptDisclaimerRequest;
}

export interface CreateApiConnectionOperationRequest {
    createApiConnectionRequest: CreateApiConnectionRequest;
}

export interface ExecuteApiConnectionRequestRequest {
    connectionId: string;
    apiConnectionRequestRequest: ApiConnectionRequestRequest;
}

export interface GetApiConnectionRequest {
    connectionId: string;
}

export interface UpdateApiConnectionOperationRequest {
    connectionId: string;
    updateApiConnectionRequest: UpdateApiConnectionRequest;
}

/**
 * ApiConnectionsApi - interface
 * 
 * @export
 * @interface ApiConnectionsApiInterface
 */
export interface ApiConnectionsApiInterface {
    /**
     * Creates request options for acceptApiConnectionDisclaimer without sending the request
     * @param {string} connectionId 
     * @param {AcceptDisclaimerRequest} acceptDisclaimerRequest 
     * @throws {RequiredError}
     * @memberof ApiConnectionsApiInterface
     */
    acceptApiConnectionDisclaimerRequestOpts(requestParameters: AcceptApiConnectionDisclaimerRequest): Promise<runtime.RequestOpts>;

    /**
     * Accept the egress disclaimer (Admin/Owner).
     * @summary Accept Api Connection Disclaimer Handler
     * @param {string} connectionId 
     * @param {AcceptDisclaimerRequest} acceptDisclaimerRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiConnectionsApiInterface
     */
    acceptApiConnectionDisclaimerRaw(requestParameters: AcceptApiConnectionDisclaimerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiConnectionResponse>>;

    /**
     * Accept the egress disclaimer (Admin/Owner).
     * Accept Api Connection Disclaimer Handler
     */
    acceptApiConnectionDisclaimer(requestParameters: AcceptApiConnectionDisclaimerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiConnectionResponse>;

    /**
     * Creates request options for createApiConnection without sending the request
     * @param {CreateApiConnectionRequest} createApiConnectionRequest 
     * @throws {RequiredError}
     * @memberof ApiConnectionsApiInterface
     */
    createApiConnectionRequestOpts(requestParameters: CreateApiConnectionOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Create a connection under a writable folder (Admin/Owner; egress on).
     * @summary Create Api Connection Handler
     * @param {CreateApiConnectionRequest} createApiConnectionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiConnectionsApiInterface
     */
    createApiConnectionRaw(requestParameters: CreateApiConnectionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiConnectionResponse>>;

    /**
     * Create a connection under a writable folder (Admin/Owner; egress on).
     * Create Api Connection Handler
     */
    createApiConnection(requestParameters: CreateApiConnectionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiConnectionResponse>;

    /**
     * Creates request options for executeApiConnectionRequest without sending the request
     * @param {string} connectionId 
     * @param {ApiConnectionRequestRequest} apiConnectionRequestRequest 
     * @throws {RequiredError}
     * @memberof ApiConnectionsApiInterface
     */
    executeApiConnectionRequestRequestOpts(requestParameters: ExecuteApiConnectionRequestRequest): Promise<runtime.RequestOpts>;

    /**
     * Execute a safe, audited outbound request (all gates run in the service).
     * @summary Execute Api Connection Request Handler
     * @param {string} connectionId 
     * @param {ApiConnectionRequestRequest} apiConnectionRequestRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiConnectionsApiInterface
     */
    executeApiConnectionRequestRaw(requestParameters: ExecuteApiConnectionRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiConnectionRequestResponse>>;

    /**
     * Execute a safe, audited outbound request (all gates run in the service).
     * Execute Api Connection Request Handler
     */
    executeApiConnectionRequest(requestParameters: ExecuteApiConnectionRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiConnectionRequestResponse>;

    /**
     * Creates request options for getApiConnection without sending the request
     * @param {string} connectionId 
     * @throws {RequiredError}
     * @memberof ApiConnectionsApiInterface
     */
    getApiConnectionRequestOpts(requestParameters: GetApiConnectionRequest): Promise<runtime.RequestOpts>;

    /**
     * Get a connection (no secret); requires read access.
     * @summary Get Api Connection Handler
     * @param {string} connectionId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiConnectionsApiInterface
     */
    getApiConnectionRaw(requestParameters: GetApiConnectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiConnectionResponse>>;

    /**
     * Get a connection (no secret); requires read access.
     * Get Api Connection Handler
     */
    getApiConnection(requestParameters: GetApiConnectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiConnectionResponse>;

    /**
     * Creates request options for updateApiConnection without sending the request
     * @param {string} connectionId 
     * @param {UpdateApiConnectionRequest} updateApiConnectionRequest 
     * @throws {RequiredError}
     * @memberof ApiConnectionsApiInterface
     */
    updateApiConnectionRequestOpts(requestParameters: UpdateApiConnectionOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Update a connection (Admin/Owner). A risk-up change re-arms the disclaimer.
     * @summary Update Api Connection Handler
     * @param {string} connectionId 
     * @param {UpdateApiConnectionRequest} updateApiConnectionRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ApiConnectionsApiInterface
     */
    updateApiConnectionRaw(requestParameters: UpdateApiConnectionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiConnectionResponse>>;

    /**
     * Update a connection (Admin/Owner). A risk-up change re-arms the disclaimer.
     * Update Api Connection Handler
     */
    updateApiConnection(requestParameters: UpdateApiConnectionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiConnectionResponse>;

}

/**
 * 
 */
export class ApiConnectionsApi extends runtime.BaseAPI implements ApiConnectionsApiInterface {

    /**
     * Creates request options for acceptApiConnectionDisclaimer without sending the request
     */
    async acceptApiConnectionDisclaimerRequestOpts(requestParameters: AcceptApiConnectionDisclaimerRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['connectionId'] == null) {
            throw new runtime.RequiredError(
                'connectionId',
                'Required parameter "connectionId" was null or undefined when calling acceptApiConnectionDisclaimer().'
            );
        }

        if (requestParameters['acceptDisclaimerRequest'] == null) {
            throw new runtime.RequiredError(
                'acceptDisclaimerRequest',
                'Required parameter "acceptDisclaimerRequest" was null or undefined when calling acceptApiConnectionDisclaimer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/api-connections/{connection_id}/disclaimer`;
        urlPath = urlPath.replace(`{${"connection_id"}}`, encodeURIComponent(String(requestParameters['connectionId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AcceptDisclaimerRequestToJSON(requestParameters['acceptDisclaimerRequest']),
        };
    }

    /**
     * Accept the egress disclaimer (Admin/Owner).
     * Accept Api Connection Disclaimer Handler
     */
    async acceptApiConnectionDisclaimerRaw(requestParameters: AcceptApiConnectionDisclaimerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiConnectionResponse>> {
        const requestOptions = await this.acceptApiConnectionDisclaimerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiConnectionResponseFromJSON(jsonValue));
    }

    /**
     * Accept the egress disclaimer (Admin/Owner).
     * Accept Api Connection Disclaimer Handler
     */
    async acceptApiConnectionDisclaimer(requestParameters: AcceptApiConnectionDisclaimerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiConnectionResponse> {
        const response = await this.acceptApiConnectionDisclaimerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createApiConnection without sending the request
     */
    async createApiConnectionRequestOpts(requestParameters: CreateApiConnectionOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createApiConnectionRequest'] == null) {
            throw new runtime.RequiredError(
                'createApiConnectionRequest',
                'Required parameter "createApiConnectionRequest" was null or undefined when calling createApiConnection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/api-connections`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateApiConnectionRequestToJSON(requestParameters['createApiConnectionRequest']),
        };
    }

    /**
     * Create a connection under a writable folder (Admin/Owner; egress on).
     * Create Api Connection Handler
     */
    async createApiConnectionRaw(requestParameters: CreateApiConnectionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiConnectionResponse>> {
        const requestOptions = await this.createApiConnectionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiConnectionResponseFromJSON(jsonValue));
    }

    /**
     * Create a connection under a writable folder (Admin/Owner; egress on).
     * Create Api Connection Handler
     */
    async createApiConnection(requestParameters: CreateApiConnectionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiConnectionResponse> {
        const response = await this.createApiConnectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for executeApiConnectionRequest without sending the request
     */
    async executeApiConnectionRequestRequestOpts(requestParameters: ExecuteApiConnectionRequestRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['connectionId'] == null) {
            throw new runtime.RequiredError(
                'connectionId',
                'Required parameter "connectionId" was null or undefined when calling executeApiConnectionRequest().'
            );
        }

        if (requestParameters['apiConnectionRequestRequest'] == null) {
            throw new runtime.RequiredError(
                'apiConnectionRequestRequest',
                'Required parameter "apiConnectionRequestRequest" was null or undefined when calling executeApiConnectionRequest().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/api-connections/{connection_id}/request`;
        urlPath = urlPath.replace(`{${"connection_id"}}`, encodeURIComponent(String(requestParameters['connectionId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ApiConnectionRequestRequestToJSON(requestParameters['apiConnectionRequestRequest']),
        };
    }

    /**
     * Execute a safe, audited outbound request (all gates run in the service).
     * Execute Api Connection Request Handler
     */
    async executeApiConnectionRequestRaw(requestParameters: ExecuteApiConnectionRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiConnectionRequestResponse>> {
        const requestOptions = await this.executeApiConnectionRequestRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiConnectionRequestResponseFromJSON(jsonValue));
    }

    /**
     * Execute a safe, audited outbound request (all gates run in the service).
     * Execute Api Connection Request Handler
     */
    async executeApiConnectionRequest(requestParameters: ExecuteApiConnectionRequestRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiConnectionRequestResponse> {
        const response = await this.executeApiConnectionRequestRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getApiConnection without sending the request
     */
    async getApiConnectionRequestOpts(requestParameters: GetApiConnectionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['connectionId'] == null) {
            throw new runtime.RequiredError(
                'connectionId',
                'Required parameter "connectionId" was null or undefined when calling getApiConnection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/api-connections/{connection_id}`;
        urlPath = urlPath.replace(`{${"connection_id"}}`, encodeURIComponent(String(requestParameters['connectionId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a connection (no secret); requires read access.
     * Get Api Connection Handler
     */
    async getApiConnectionRaw(requestParameters: GetApiConnectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiConnectionResponse>> {
        const requestOptions = await this.getApiConnectionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiConnectionResponseFromJSON(jsonValue));
    }

    /**
     * Get a connection (no secret); requires read access.
     * Get Api Connection Handler
     */
    async getApiConnection(requestParameters: GetApiConnectionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiConnectionResponse> {
        const response = await this.getApiConnectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateApiConnection without sending the request
     */
    async updateApiConnectionRequestOpts(requestParameters: UpdateApiConnectionOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['connectionId'] == null) {
            throw new runtime.RequiredError(
                'connectionId',
                'Required parameter "connectionId" was null or undefined when calling updateApiConnection().'
            );
        }

        if (requestParameters['updateApiConnectionRequest'] == null) {
            throw new runtime.RequiredError(
                'updateApiConnectionRequest',
                'Required parameter "updateApiConnectionRequest" was null or undefined when calling updateApiConnection().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/api-connections/{connection_id}`;
        urlPath = urlPath.replace(`{${"connection_id"}}`, encodeURIComponent(String(requestParameters['connectionId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateApiConnectionRequestToJSON(requestParameters['updateApiConnectionRequest']),
        };
    }

    /**
     * Update a connection (Admin/Owner). A risk-up change re-arms the disclaimer.
     * Update Api Connection Handler
     */
    async updateApiConnectionRaw(requestParameters: UpdateApiConnectionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiConnectionResponse>> {
        const requestOptions = await this.updateApiConnectionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiConnectionResponseFromJSON(jsonValue));
    }

    /**
     * Update a connection (Admin/Owner). A risk-up change re-arms the disclaimer.
     * Update Api Connection Handler
     */
    async updateApiConnection(requestParameters: UpdateApiConnectionOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiConnectionResponse> {
        const response = await this.updateApiConnectionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
