/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Stack API
 * Knowledge Stack backend API for authentication and knowledge management
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  BillingPlanResponse,
  CreateCheckoutSessionRequest,
  CreateCheckoutSessionResponse,
  CreatePortalSessionRequest,
  CreatePortalSessionResponse,
  HTTPValidationError,
  SetEnterpriseOverrideRequest,
  TenantSubscriptionResponse,
  TenantUsageResponse,
  UserUsageResponse,
} from '../models/index';
import {
    BillingPlanResponseFromJSON,
    BillingPlanResponseToJSON,
    CreateCheckoutSessionRequestFromJSON,
    CreateCheckoutSessionRequestToJSON,
    CreateCheckoutSessionResponseFromJSON,
    CreateCheckoutSessionResponseToJSON,
    CreatePortalSessionRequestFromJSON,
    CreatePortalSessionRequestToJSON,
    CreatePortalSessionResponseFromJSON,
    CreatePortalSessionResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    SetEnterpriseOverrideRequestFromJSON,
    SetEnterpriseOverrideRequestToJSON,
    TenantSubscriptionResponseFromJSON,
    TenantSubscriptionResponseToJSON,
    TenantUsageResponseFromJSON,
    TenantUsageResponseToJSON,
    UserUsageResponseFromJSON,
    UserUsageResponseToJSON,
} from '../models/index';

export interface AdminClearEnterpriseOverrideRequest {
    tenantId: string;
    xKSPlatformAdminKey?: string | null;
}

export interface AdminSetEnterpriseOverrideRequest {
    tenantId: string;
    setEnterpriseOverrideRequest: SetEnterpriseOverrideRequest;
    xKSPlatformAdminKey?: string | null;
}

export interface CancelTenantSubscriptionRequest {
    authorization?: string | null;
    ksUat?: string | null;
}

export interface CreateBillingCheckoutSessionRequest {
    createCheckoutSessionRequest: CreateCheckoutSessionRequest;
    authorization?: string | null;
    ksUat?: string | null;
}

export interface CreateBillingPortalSessionRequest {
    createPortalSessionRequest: CreatePortalSessionRequest;
    authorization?: string | null;
    ksUat?: string | null;
}

export interface GetCurrentUserUsageRequest {
    authorization?: string | null;
    ksUat?: string | null;
}

export interface GetTenantSubscriptionRequest {
    authorization?: string | null;
    ksUat?: string | null;
}

export interface GetTenantUsageRequest {
    authorization?: string | null;
    ksUat?: string | null;
}

export interface ListBillingPlansRequest {
    authorization?: string | null;
    ksUat?: string | null;
}

export interface ResumeTenantSubscriptionRequest {
    authorization?: string | null;
    ksUat?: string | null;
}

/**
 * BillingApi - interface
 * 
 * @export
 * @interface BillingApiInterface
 */
export interface BillingApiInterface {
    /**
     * Creates request options for adminClearEnterpriseOverride without sending the request
     * @param {string} tenantId 
     * @param {string} [xKSPlatformAdminKey] 
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    adminClearEnterpriseOverrideRequestOpts(requestParameters: AdminClearEnterpriseOverrideRequest): Promise<runtime.RequestOpts>;

    /**
     * Clear all enterprise overrides for a tenant (contract ended).
     * @summary Admin Clear Enterprise Override Handler
     * @param {string} tenantId 
     * @param {string} [xKSPlatformAdminKey] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    adminClearEnterpriseOverrideRaw(requestParameters: AdminClearEnterpriseOverrideRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TenantSubscriptionResponse>>;

    /**
     * Clear all enterprise overrides for a tenant (contract ended).
     * Admin Clear Enterprise Override Handler
     */
    adminClearEnterpriseOverride(requestParameters: AdminClearEnterpriseOverrideRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TenantSubscriptionResponse>;

    /**
     * Creates request options for adminSetEnterpriseOverride without sending the request
     * @param {string} tenantId 
     * @param {SetEnterpriseOverrideRequest} setEnterpriseOverrideRequest 
     * @param {string} [xKSPlatformAdminKey] 
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    adminSetEnterpriseOverrideRequestOpts(requestParameters: AdminSetEnterpriseOverrideRequest): Promise<runtime.RequestOpts>;

    /**
     * Set per-tenant enterprise contract overrides (custom pricing/limits).
     * @summary Admin Set Enterprise Override Handler
     * @param {string} tenantId 
     * @param {SetEnterpriseOverrideRequest} setEnterpriseOverrideRequest 
     * @param {string} [xKSPlatformAdminKey] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    adminSetEnterpriseOverrideRaw(requestParameters: AdminSetEnterpriseOverrideRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TenantSubscriptionResponse>>;

    /**
     * Set per-tenant enterprise contract overrides (custom pricing/limits).
     * Admin Set Enterprise Override Handler
     */
    adminSetEnterpriseOverride(requestParameters: AdminSetEnterpriseOverrideRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TenantSubscriptionResponse>;

    /**
     * Creates request options for cancelTenantSubscription without sending the request
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    cancelTenantSubscriptionRequestOpts(requestParameters: CancelTenantSubscriptionRequest): Promise<runtime.RequestOpts>;

    /**
     * Cancel subscription at end of current period.
     * @summary Cancel Tenant Subscription Handler
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    cancelTenantSubscriptionRaw(requestParameters: CancelTenantSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TenantSubscriptionResponse>>;

    /**
     * Cancel subscription at end of current period.
     * Cancel Tenant Subscription Handler
     */
    cancelTenantSubscription(requestParameters: CancelTenantSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TenantSubscriptionResponse>;

    /**
     * Creates request options for createBillingCheckoutSession without sending the request
     * @param {CreateCheckoutSessionRequest} createCheckoutSessionRequest 
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    createBillingCheckoutSessionRequestOpts(requestParameters: CreateBillingCheckoutSessionRequest): Promise<runtime.RequestOpts>;

    /**
     * Create a Stripe Checkout session for upgrading to a paid plan.
     * @summary Create Billing Checkout Session Handler
     * @param {CreateCheckoutSessionRequest} createCheckoutSessionRequest 
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    createBillingCheckoutSessionRaw(requestParameters: CreateBillingCheckoutSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateCheckoutSessionResponse>>;

    /**
     * Create a Stripe Checkout session for upgrading to a paid plan.
     * Create Billing Checkout Session Handler
     */
    createBillingCheckoutSession(requestParameters: CreateBillingCheckoutSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateCheckoutSessionResponse>;

    /**
     * Creates request options for createBillingPortalSession without sending the request
     * @param {CreatePortalSessionRequest} createPortalSessionRequest 
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    createBillingPortalSessionRequestOpts(requestParameters: CreateBillingPortalSessionRequest): Promise<runtime.RequestOpts>;

    /**
     * Create a Stripe billing portal session (manage payment method, cancel).
     * @summary Create Billing Portal Session Handler
     * @param {CreatePortalSessionRequest} createPortalSessionRequest 
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    createBillingPortalSessionRaw(requestParameters: CreateBillingPortalSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreatePortalSessionResponse>>;

    /**
     * Create a Stripe billing portal session (manage payment method, cancel).
     * Create Billing Portal Session Handler
     */
    createBillingPortalSession(requestParameters: CreateBillingPortalSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreatePortalSessionResponse>;

    /**
     * Creates request options for getCurrentUserUsage without sending the request
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    getCurrentUserUsageRequestOpts(requestParameters: GetCurrentUserUsageRequest): Promise<runtime.RequestOpts>;

    /**
     * Current user\'s own usage for this period (any authenticated user).
     * @summary Get Current User Usage Handler
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    getCurrentUserUsageRaw(requestParameters: GetCurrentUserUsageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserUsageResponse>>;

    /**
     * Current user\'s own usage for this period (any authenticated user).
     * Get Current User Usage Handler
     */
    getCurrentUserUsage(requestParameters: GetCurrentUserUsageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserUsageResponse>;

    /**
     * Creates request options for getTenantSubscription without sending the request
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    getTenantSubscriptionRequestOpts(requestParameters: GetTenantSubscriptionRequest): Promise<runtime.RequestOpts>;

    /**
     * Fetch the tenant\'s current subscription (any authenticated user).
     * @summary Get Tenant Subscription Handler
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    getTenantSubscriptionRaw(requestParameters: GetTenantSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TenantSubscriptionResponse>>;

    /**
     * Fetch the tenant\'s current subscription (any authenticated user).
     * Get Tenant Subscription Handler
     */
    getTenantSubscription(requestParameters: GetTenantSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TenantSubscriptionResponse>;

    /**
     * Creates request options for getTenantUsage without sending the request
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    getTenantUsageRequestOpts(requestParameters: GetTenantUsageRequest): Promise<runtime.RequestOpts>;

    /**
     * Tenant-wide usage (OWNER/ADMIN only).
     * @summary Get Tenant Usage Handler
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    getTenantUsageRaw(requestParameters: GetTenantUsageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TenantUsageResponse>>;

    /**
     * Tenant-wide usage (OWNER/ADMIN only).
     * Get Tenant Usage Handler
     */
    getTenantUsage(requestParameters: GetTenantUsageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TenantUsageResponse>;

    /**
     * Creates request options for listBillingPlans without sending the request
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    listBillingPlansRequestOpts(requestParameters: ListBillingPlansRequest): Promise<runtime.RequestOpts>;

    /**
     * List all active plans. Any authenticated user can see the catalog.
     * @summary List Billing Plans Handler
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    listBillingPlansRaw(requestParameters: ListBillingPlansRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BillingPlanResponse>>>;

    /**
     * List all active plans. Any authenticated user can see the catalog.
     * List Billing Plans Handler
     */
    listBillingPlans(requestParameters: ListBillingPlansRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BillingPlanResponse>>;

    /**
     * Creates request options for resumeTenantSubscription without sending the request
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    resumeTenantSubscriptionRequestOpts(requestParameters: ResumeTenantSubscriptionRequest): Promise<runtime.RequestOpts>;

    /**
     * Undo a prior cancel-at-period-end request.
     * @summary Resume Tenant Subscription Handler
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BillingApiInterface
     */
    resumeTenantSubscriptionRaw(requestParameters: ResumeTenantSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TenantSubscriptionResponse>>;

    /**
     * Undo a prior cancel-at-period-end request.
     * Resume Tenant Subscription Handler
     */
    resumeTenantSubscription(requestParameters: ResumeTenantSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TenantSubscriptionResponse>;

}

/**
 * 
 */
export class BillingApi extends runtime.BaseAPI implements BillingApiInterface {

    /**
     * Creates request options for adminClearEnterpriseOverride without sending the request
     */
    async adminClearEnterpriseOverrideRequestOpts(requestParameters: AdminClearEnterpriseOverrideRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tenantId'] == null) {
            throw new runtime.RequiredError(
                'tenantId',
                'Required parameter "tenantId" was null or undefined when calling adminClearEnterpriseOverride().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['xKSPlatformAdminKey'] != null) {
            headerParameters['X-KS-Platform-Admin-Key'] = String(requestParameters['xKSPlatformAdminKey']);
        }


        let urlPath = `/v1/billing/admin/tenants/{tenant_id}/overrides`;
        urlPath = urlPath.replace(`{${"tenant_id"}}`, encodeURIComponent(String(requestParameters['tenantId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Clear all enterprise overrides for a tenant (contract ended).
     * Admin Clear Enterprise Override Handler
     */
    async adminClearEnterpriseOverrideRaw(requestParameters: AdminClearEnterpriseOverrideRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TenantSubscriptionResponse>> {
        const requestOptions = await this.adminClearEnterpriseOverrideRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TenantSubscriptionResponseFromJSON(jsonValue));
    }

    /**
     * Clear all enterprise overrides for a tenant (contract ended).
     * Admin Clear Enterprise Override Handler
     */
    async adminClearEnterpriseOverride(requestParameters: AdminClearEnterpriseOverrideRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TenantSubscriptionResponse> {
        const response = await this.adminClearEnterpriseOverrideRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for adminSetEnterpriseOverride without sending the request
     */
    async adminSetEnterpriseOverrideRequestOpts(requestParameters: AdminSetEnterpriseOverrideRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['tenantId'] == null) {
            throw new runtime.RequiredError(
                'tenantId',
                'Required parameter "tenantId" was null or undefined when calling adminSetEnterpriseOverride().'
            );
        }

        if (requestParameters['setEnterpriseOverrideRequest'] == null) {
            throw new runtime.RequiredError(
                'setEnterpriseOverrideRequest',
                'Required parameter "setEnterpriseOverrideRequest" was null or undefined when calling adminSetEnterpriseOverride().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xKSPlatformAdminKey'] != null) {
            headerParameters['X-KS-Platform-Admin-Key'] = String(requestParameters['xKSPlatformAdminKey']);
        }


        let urlPath = `/v1/billing/admin/tenants/{tenant_id}/overrides`;
        urlPath = urlPath.replace(`{${"tenant_id"}}`, encodeURIComponent(String(requestParameters['tenantId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: SetEnterpriseOverrideRequestToJSON(requestParameters['setEnterpriseOverrideRequest']),
        };
    }

    /**
     * Set per-tenant enterprise contract overrides (custom pricing/limits).
     * Admin Set Enterprise Override Handler
     */
    async adminSetEnterpriseOverrideRaw(requestParameters: AdminSetEnterpriseOverrideRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TenantSubscriptionResponse>> {
        const requestOptions = await this.adminSetEnterpriseOverrideRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TenantSubscriptionResponseFromJSON(jsonValue));
    }

    /**
     * Set per-tenant enterprise contract overrides (custom pricing/limits).
     * Admin Set Enterprise Override Handler
     */
    async adminSetEnterpriseOverride(requestParameters: AdminSetEnterpriseOverrideRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TenantSubscriptionResponse> {
        const response = await this.adminSetEnterpriseOverrideRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for cancelTenantSubscription without sending the request
     */
    async cancelTenantSubscriptionRequestOpts(requestParameters: CancelTenantSubscriptionRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/billing/subscription/cancel`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Cancel subscription at end of current period.
     * Cancel Tenant Subscription Handler
     */
    async cancelTenantSubscriptionRaw(requestParameters: CancelTenantSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TenantSubscriptionResponse>> {
        const requestOptions = await this.cancelTenantSubscriptionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TenantSubscriptionResponseFromJSON(jsonValue));
    }

    /**
     * Cancel subscription at end of current period.
     * Cancel Tenant Subscription Handler
     */
    async cancelTenantSubscription(requestParameters: CancelTenantSubscriptionRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TenantSubscriptionResponse> {
        const response = await this.cancelTenantSubscriptionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createBillingCheckoutSession without sending the request
     */
    async createBillingCheckoutSessionRequestOpts(requestParameters: CreateBillingCheckoutSessionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createCheckoutSessionRequest'] == null) {
            throw new runtime.RequiredError(
                'createCheckoutSessionRequest',
                'Required parameter "createCheckoutSessionRequest" was null or undefined when calling createBillingCheckoutSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/billing/checkout-session`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCheckoutSessionRequestToJSON(requestParameters['createCheckoutSessionRequest']),
        };
    }

    /**
     * Create a Stripe Checkout session for upgrading to a paid plan.
     * Create Billing Checkout Session Handler
     */
    async createBillingCheckoutSessionRaw(requestParameters: CreateBillingCheckoutSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreateCheckoutSessionResponse>> {
        const requestOptions = await this.createBillingCheckoutSessionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreateCheckoutSessionResponseFromJSON(jsonValue));
    }

    /**
     * Create a Stripe Checkout session for upgrading to a paid plan.
     * Create Billing Checkout Session Handler
     */
    async createBillingCheckoutSession(requestParameters: CreateBillingCheckoutSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreateCheckoutSessionResponse> {
        const response = await this.createBillingCheckoutSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createBillingPortalSession without sending the request
     */
    async createBillingPortalSessionRequestOpts(requestParameters: CreateBillingPortalSessionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createPortalSessionRequest'] == null) {
            throw new runtime.RequiredError(
                'createPortalSessionRequest',
                'Required parameter "createPortalSessionRequest" was null or undefined when calling createBillingPortalSession().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/billing/portal-session`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreatePortalSessionRequestToJSON(requestParameters['createPortalSessionRequest']),
        };
    }

    /**
     * Create a Stripe billing portal session (manage payment method, cancel).
     * Create Billing Portal Session Handler
     */
    async createBillingPortalSessionRaw(requestParameters: CreateBillingPortalSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CreatePortalSessionResponse>> {
        const requestOptions = await this.createBillingPortalSessionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CreatePortalSessionResponseFromJSON(jsonValue));
    }

    /**
     * Create a Stripe billing portal session (manage payment method, cancel).
     * Create Billing Portal Session Handler
     */
    async createBillingPortalSession(requestParameters: CreateBillingPortalSessionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CreatePortalSessionResponse> {
        const response = await this.createBillingPortalSessionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getCurrentUserUsage without sending the request
     */
    async getCurrentUserUsageRequestOpts(requestParameters: GetCurrentUserUsageRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/billing/usage/me`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Current user\'s own usage for this period (any authenticated user).
     * Get Current User Usage Handler
     */
    async getCurrentUserUsageRaw(requestParameters: GetCurrentUserUsageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserUsageResponse>> {
        const requestOptions = await this.getCurrentUserUsageRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserUsageResponseFromJSON(jsonValue));
    }

    /**
     * Current user\'s own usage for this period (any authenticated user).
     * Get Current User Usage Handler
     */
    async getCurrentUserUsage(requestParameters: GetCurrentUserUsageRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserUsageResponse> {
        const response = await this.getCurrentUserUsageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTenantSubscription without sending the request
     */
    async getTenantSubscriptionRequestOpts(requestParameters: GetTenantSubscriptionRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/billing/subscription`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Fetch the tenant\'s current subscription (any authenticated user).
     * Get Tenant Subscription Handler
     */
    async getTenantSubscriptionRaw(requestParameters: GetTenantSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TenantSubscriptionResponse>> {
        const requestOptions = await this.getTenantSubscriptionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TenantSubscriptionResponseFromJSON(jsonValue));
    }

    /**
     * Fetch the tenant\'s current subscription (any authenticated user).
     * Get Tenant Subscription Handler
     */
    async getTenantSubscription(requestParameters: GetTenantSubscriptionRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TenantSubscriptionResponse> {
        const response = await this.getTenantSubscriptionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getTenantUsage without sending the request
     */
    async getTenantUsageRequestOpts(requestParameters: GetTenantUsageRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/billing/usage`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Tenant-wide usage (OWNER/ADMIN only).
     * Get Tenant Usage Handler
     */
    async getTenantUsageRaw(requestParameters: GetTenantUsageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TenantUsageResponse>> {
        const requestOptions = await this.getTenantUsageRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TenantUsageResponseFromJSON(jsonValue));
    }

    /**
     * Tenant-wide usage (OWNER/ADMIN only).
     * Get Tenant Usage Handler
     */
    async getTenantUsage(requestParameters: GetTenantUsageRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TenantUsageResponse> {
        const response = await this.getTenantUsageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listBillingPlans without sending the request
     */
    async listBillingPlansRequestOpts(requestParameters: ListBillingPlansRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/billing/plans`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all active plans. Any authenticated user can see the catalog.
     * List Billing Plans Handler
     */
    async listBillingPlansRaw(requestParameters: ListBillingPlansRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BillingPlanResponse>>> {
        const requestOptions = await this.listBillingPlansRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BillingPlanResponseFromJSON));
    }

    /**
     * List all active plans. Any authenticated user can see the catalog.
     * List Billing Plans Handler
     */
    async listBillingPlans(requestParameters: ListBillingPlansRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BillingPlanResponse>> {
        const response = await this.listBillingPlansRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for resumeTenantSubscription without sending the request
     */
    async resumeTenantSubscriptionRequestOpts(requestParameters: ResumeTenantSubscriptionRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/billing/subscription/resume`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Undo a prior cancel-at-period-end request.
     * Resume Tenant Subscription Handler
     */
    async resumeTenantSubscriptionRaw(requestParameters: ResumeTenantSubscriptionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TenantSubscriptionResponse>> {
        const requestOptions = await this.resumeTenantSubscriptionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TenantSubscriptionResponseFromJSON(jsonValue));
    }

    /**
     * Undo a prior cancel-at-period-end request.
     * Resume Tenant Subscription Handler
     */
    async resumeTenantSubscription(requestParameters: ResumeTenantSubscriptionRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TenantSubscriptionResponse> {
        const response = await this.resumeTenantSubscriptionRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
