/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Stack API
 * Knowledge Stack backend API for authentication and knowledge management
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  HTTPValidationError,
  MemoryBodyResponse,
  MemoryChunkResponse,
  MemoryScope,
  PaginatedResponsePendingMemoryChunkResponse,
  ProposeMemoryChunkRequest,
  ProposedMemoryChunkResponse,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    MemoryBodyResponseFromJSON,
    MemoryBodyResponseToJSON,
    MemoryChunkResponseFromJSON,
    MemoryChunkResponseToJSON,
    MemoryScopeFromJSON,
    MemoryScopeToJSON,
    PaginatedResponsePendingMemoryChunkResponseFromJSON,
    PaginatedResponsePendingMemoryChunkResponseToJSON,
    ProposeMemoryChunkRequestFromJSON,
    ProposeMemoryChunkRequestToJSON,
    ProposedMemoryChunkResponseFromJSON,
    ProposedMemoryChunkResponseToJSON,
} from '../models/index';

export interface ApproveMemoryProposalRequest {
    chunkId: string;
}

export interface GetMemoryBodyRequest {
    scope: MemoryScope;
    ownerId: string;
}

export interface ListMemoryProposalsRequest {
    limit?: number;
    offset?: number;
}

export interface ProposeMemoryChunkOperationRequest {
    proposeMemoryChunkRequest: ProposeMemoryChunkRequest;
}

export interface RejectMemoryProposalRequest {
    chunkId: string;
}

/**
 * MemoryApi - interface
 * 
 * @export
 * @interface MemoryApiInterface
 */
export interface MemoryApiInterface {
    /**
     * Creates request options for approveMemoryProposal without sending the request
     * @param {string} chunkId 
     * @throws {RequiredError}
     * @memberof MemoryApiInterface
     */
    approveMemoryProposalRequestOpts(requestParameters: ApproveMemoryProposalRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Approve Memory Proposal Handler
     * @param {string} chunkId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemoryApiInterface
     */
    approveMemoryProposalRaw(requestParameters: ApproveMemoryProposalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MemoryChunkResponse>>;

    /**
     * Approve Memory Proposal Handler
     */
    approveMemoryProposal(requestParameters: ApproveMemoryProposalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MemoryChunkResponse>;

    /**
     * Creates request options for getMemoryBody without sending the request
     * @param {MemoryScope} scope 
     * @param {string} ownerId 
     * @throws {RequiredError}
     * @memberof MemoryApiInterface
     */
    getMemoryBodyRequestOpts(requestParameters: GetMemoryBodyRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Get Memory Body Handler
     * @param {MemoryScope} scope 
     * @param {string} ownerId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemoryApiInterface
     */
    getMemoryBodyRaw(requestParameters: GetMemoryBodyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MemoryBodyResponse>>;

    /**
     * Get Memory Body Handler
     */
    getMemoryBody(requestParameters: GetMemoryBodyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MemoryBodyResponse>;

    /**
     * Creates request options for listMemoryProposals without sending the request
     * @param {number} [limit] Number of items per page
     * @param {number} [offset] Number of items to skip
     * @throws {RequiredError}
     * @memberof MemoryApiInterface
     */
    listMemoryProposalsRequestOpts(requestParameters: ListMemoryProposalsRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary List Memory Proposals Handler
     * @param {number} [limit] Number of items per page
     * @param {number} [offset] Number of items to skip
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemoryApiInterface
     */
    listMemoryProposalsRaw(requestParameters: ListMemoryProposalsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedResponsePendingMemoryChunkResponse>>;

    /**
     * List Memory Proposals Handler
     */
    listMemoryProposals(requestParameters: ListMemoryProposalsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedResponsePendingMemoryChunkResponse>;

    /**
     * Creates request options for proposeMemoryChunk without sending the request
     * @param {ProposeMemoryChunkRequest} proposeMemoryChunkRequest 
     * @throws {RequiredError}
     * @memberof MemoryApiInterface
     */
    proposeMemoryChunkRequestOpts(requestParameters: ProposeMemoryChunkOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Propose Memory Chunk Handler
     * @param {ProposeMemoryChunkRequest} proposeMemoryChunkRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemoryApiInterface
     */
    proposeMemoryChunkRaw(requestParameters: ProposeMemoryChunkOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProposedMemoryChunkResponse>>;

    /**
     * Propose Memory Chunk Handler
     */
    proposeMemoryChunk(requestParameters: ProposeMemoryChunkOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProposedMemoryChunkResponse>;

    /**
     * Creates request options for rejectMemoryProposal without sending the request
     * @param {string} chunkId 
     * @throws {RequiredError}
     * @memberof MemoryApiInterface
     */
    rejectMemoryProposalRequestOpts(requestParameters: RejectMemoryProposalRequest): Promise<runtime.RequestOpts>;

    /**
     * 
     * @summary Reject Memory Proposal Handler
     * @param {string} chunkId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof MemoryApiInterface
     */
    rejectMemoryProposalRaw(requestParameters: RejectMemoryProposalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Reject Memory Proposal Handler
     */
    rejectMemoryProposal(requestParameters: RejectMemoryProposalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

}

/**
 * 
 */
export class MemoryApi extends runtime.BaseAPI implements MemoryApiInterface {

    /**
     * Creates request options for approveMemoryProposal without sending the request
     */
    async approveMemoryProposalRequestOpts(requestParameters: ApproveMemoryProposalRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['chunkId'] == null) {
            throw new runtime.RequiredError(
                'chunkId',
                'Required parameter "chunkId" was null or undefined when calling approveMemoryProposal().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/memory/proposals/{chunk_id}/approve`;
        urlPath = urlPath.replace(`{${"chunk_id"}}`, encodeURIComponent(String(requestParameters['chunkId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Approve Memory Proposal Handler
     */
    async approveMemoryProposalRaw(requestParameters: ApproveMemoryProposalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MemoryChunkResponse>> {
        const requestOptions = await this.approveMemoryProposalRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MemoryChunkResponseFromJSON(jsonValue));
    }

    /**
     * Approve Memory Proposal Handler
     */
    async approveMemoryProposal(requestParameters: ApproveMemoryProposalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MemoryChunkResponse> {
        const response = await this.approveMemoryProposalRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getMemoryBody without sending the request
     */
    async getMemoryBodyRequestOpts(requestParameters: GetMemoryBodyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['scope'] == null) {
            throw new runtime.RequiredError(
                'scope',
                'Required parameter "scope" was null or undefined when calling getMemoryBody().'
            );
        }

        if (requestParameters['ownerId'] == null) {
            throw new runtime.RequiredError(
                'ownerId',
                'Required parameter "ownerId" was null or undefined when calling getMemoryBody().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['scope'] != null) {
            queryParameters['scope'] = requestParameters['scope'];
        }

        if (requestParameters['ownerId'] != null) {
            queryParameters['owner_id'] = requestParameters['ownerId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/memory/body`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get Memory Body Handler
     */
    async getMemoryBodyRaw(requestParameters: GetMemoryBodyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MemoryBodyResponse>> {
        const requestOptions = await this.getMemoryBodyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MemoryBodyResponseFromJSON(jsonValue));
    }

    /**
     * Get Memory Body Handler
     */
    async getMemoryBody(requestParameters: GetMemoryBodyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MemoryBodyResponse> {
        const response = await this.getMemoryBodyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listMemoryProposals without sending the request
     */
    async listMemoryProposalsRequestOpts(requestParameters: ListMemoryProposalsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/memory/proposals`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List Memory Proposals Handler
     */
    async listMemoryProposalsRaw(requestParameters: ListMemoryProposalsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedResponsePendingMemoryChunkResponse>> {
        const requestOptions = await this.listMemoryProposalsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedResponsePendingMemoryChunkResponseFromJSON(jsonValue));
    }

    /**
     * List Memory Proposals Handler
     */
    async listMemoryProposals(requestParameters: ListMemoryProposalsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedResponsePendingMemoryChunkResponse> {
        const response = await this.listMemoryProposalsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for proposeMemoryChunk without sending the request
     */
    async proposeMemoryChunkRequestOpts(requestParameters: ProposeMemoryChunkOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['proposeMemoryChunkRequest'] == null) {
            throw new runtime.RequiredError(
                'proposeMemoryChunkRequest',
                'Required parameter "proposeMemoryChunkRequest" was null or undefined when calling proposeMemoryChunk().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/memory/proposals`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProposeMemoryChunkRequestToJSON(requestParameters['proposeMemoryChunkRequest']),
        };
    }

    /**
     * Propose Memory Chunk Handler
     */
    async proposeMemoryChunkRaw(requestParameters: ProposeMemoryChunkOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProposedMemoryChunkResponse>> {
        const requestOptions = await this.proposeMemoryChunkRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProposedMemoryChunkResponseFromJSON(jsonValue));
    }

    /**
     * Propose Memory Chunk Handler
     */
    async proposeMemoryChunk(requestParameters: ProposeMemoryChunkOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProposedMemoryChunkResponse> {
        const response = await this.proposeMemoryChunkRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for rejectMemoryProposal without sending the request
     */
    async rejectMemoryProposalRequestOpts(requestParameters: RejectMemoryProposalRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['chunkId'] == null) {
            throw new runtime.RequiredError(
                'chunkId',
                'Required parameter "chunkId" was null or undefined when calling rejectMemoryProposal().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/v1/memory/proposals/{chunk_id}/reject`;
        urlPath = urlPath.replace(`{${"chunk_id"}}`, encodeURIComponent(String(requestParameters['chunkId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Reject Memory Proposal Handler
     */
    async rejectMemoryProposalRaw(requestParameters: RejectMemoryProposalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.rejectMemoryProposalRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Reject Memory Proposal Handler
     */
    async rejectMemoryProposal(requestParameters: RejectMemoryProposalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.rejectMemoryProposalRaw(requestParameters, initOverrides);
    }

}
