/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Stack API
 * Knowledge Stack backend API for authentication and knowledge management
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateThreadRequest,
  HTTPValidationError,
  PaginatedResponseThreadResponse,
  ThreadResponse,
  UpdateThreadRequest,
  UserMessageRequest,
  UserMessageResponse,
} from '../models/index';
import {
    CreateThreadRequestFromJSON,
    CreateThreadRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    PaginatedResponseThreadResponseFromJSON,
    PaginatedResponseThreadResponseToJSON,
    ThreadResponseFromJSON,
    ThreadResponseToJSON,
    UpdateThreadRequestFromJSON,
    UpdateThreadRequestToJSON,
    UserMessageRequestFromJSON,
    UserMessageRequestToJSON,
    UserMessageResponseFromJSON,
    UserMessageResponseToJSON,
} from '../models/index';

export interface CreateThreadOperationRequest {
    createThreadRequest: CreateThreadRequest;
    authorization?: string | null;
    ksUat?: string | null;
}

export interface DeleteThreadRequest {
    threadId: string;
    authorization?: string | null;
    ksUat?: string | null;
}

export interface GetThreadRequest {
    threadId: string;
    authorization?: string | null;
    ksUat?: string | null;
}

export interface ListThreadsRequest {
    parentPathPartId?: string | null;
    limit?: number;
    offset?: number;
    authorization?: string | null;
    ksUat?: string | null;
}

export interface SendUserMessageRequest {
    threadId: string;
    userMessageRequest: UserMessageRequest;
    authorization?: string | null;
    ksUat?: string | null;
}

export interface StreamThreadRequest {
    threadId: string;
    lastMessageId?: string | null;
    lastEntryId?: string | null;
    authorization?: string | null;
    ksUat?: string | null;
}

export interface UpdateThreadOperationRequest {
    threadId: string;
    updateThreadRequest: UpdateThreadRequest;
    authorization?: string | null;
    ksUat?: string | null;
}

/**
 * ThreadsApi - interface
 * 
 * @export
 * @interface ThreadsApiInterface
 */
export interface ThreadsApiInterface {
    /**
     * Creates request options for createThread without sending the request
     * @param {CreateThreadRequest} createThreadRequest 
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @throws {RequiredError}
     * @memberof ThreadsApiInterface
     */
    createThreadRequestOpts(requestParameters: CreateThreadOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Create a new thread.  If parent_path_part_id is omitted, the thread is created under the user\'s /users/{user_id}/threads/ folder (auto-provisioned if needed).
     * @summary Create Thread Handler
     * @param {CreateThreadRequest} createThreadRequest 
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ThreadsApiInterface
     */
    createThreadRaw(requestParameters: CreateThreadOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ThreadResponse>>;

    /**
     * Create a new thread.  If parent_path_part_id is omitted, the thread is created under the user\'s /users/{user_id}/threads/ folder (auto-provisioned if needed).
     * Create Thread Handler
     */
    createThread(requestParameters: CreateThreadOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ThreadResponse>;

    /**
     * Creates request options for deleteThread without sending the request
     * @param {string} threadId 
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @throws {RequiredError}
     * @memberof ThreadsApiInterface
     */
    deleteThreadRequestOpts(requestParameters: DeleteThreadRequest): Promise<runtime.RequestOpts>;

    /**
     * Delete a thread.  Authorization: only conversation threads belonging to the current user (under /users/{user_id}/threads/) can be deleted. Asset threads (attached to documents/sections) are never deletable via this endpoint.
     * @summary Delete Thread Handler
     * @param {string} threadId 
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ThreadsApiInterface
     */
    deleteThreadRaw(requestParameters: DeleteThreadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Delete a thread.  Authorization: only conversation threads belonging to the current user (under /users/{user_id}/threads/) can be deleted. Asset threads (attached to documents/sections) are never deletable via this endpoint.
     * Delete Thread Handler
     */
    deleteThread(requestParameters: DeleteThreadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for getThread without sending the request
     * @param {string} threadId 
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @throws {RequiredError}
     * @memberof ThreadsApiInterface
     */
    getThreadRequestOpts(requestParameters: GetThreadRequest): Promise<runtime.RequestOpts>;

    /**
     * Get a thread by its thread ID.
     * @summary Get Thread Handler
     * @param {string} threadId 
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ThreadsApiInterface
     */
    getThreadRaw(requestParameters: GetThreadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ThreadResponse>>;

    /**
     * Get a thread by its thread ID.
     * Get Thread Handler
     */
    getThread(requestParameters: GetThreadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ThreadResponse>;

    /**
     * Creates request options for listThreads without sending the request
     * @param {string} [parentPathPartId] Parent PathPart ID. Omit to list user\&#39;s conversation threads.
     * @param {number} [limit] Number of items per page
     * @param {number} [offset] Number of items to skip
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @throws {RequiredError}
     * @memberof ThreadsApiInterface
     */
    listThreadsRequestOpts(requestParameters: ListThreadsRequest): Promise<runtime.RequestOpts>;

    /**
     * List threads under a parent path_part.  When parent_path_part_id is omitted, lists the authenticated user\'s conversation threads from /users/{user_id}/threads/.
     * @summary List Threads Handler
     * @param {string} [parentPathPartId] Parent PathPart ID. Omit to list user\&#39;s conversation threads.
     * @param {number} [limit] Number of items per page
     * @param {number} [offset] Number of items to skip
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ThreadsApiInterface
     */
    listThreadsRaw(requestParameters: ListThreadsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedResponseThreadResponse>>;

    /**
     * List threads under a parent path_part.  When parent_path_part_id is omitted, lists the authenticated user\'s conversation threads from /users/{user_id}/threads/.
     * List Threads Handler
     */
    listThreads(requestParameters: ListThreadsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedResponseThreadResponse>;

    /**
     * Creates request options for sendUserMessage without sending the request
     * @param {string} threadId 
     * @param {UserMessageRequest} userMessageRequest 
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @throws {RequiredError}
     * @memberof ThreadsApiInterface
     */
    sendUserMessageRequestOpts(requestParameters: SendUserMessageRequest): Promise<runtime.RequestOpts>;

    /**
     * Send a user message and trigger agent generation. Returns immediately with a workflow_id.  Connect to GET /{thread_id}/stream (SSE) before or after calling this endpoint to receive the streamed output.
     * @summary Send User Message Handler
     * @param {string} threadId 
     * @param {UserMessageRequest} userMessageRequest 
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ThreadsApiInterface
     */
    sendUserMessageRaw(requestParameters: SendUserMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserMessageResponse>>;

    /**
     * Send a user message and trigger agent generation. Returns immediately with a workflow_id.  Connect to GET /{thread_id}/stream (SSE) before or after calling this endpoint to receive the streamed output.
     * Send User Message Handler
     */
    sendUserMessage(requestParameters: SendUserMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserMessageResponse>;

    /**
     * Creates request options for streamThread without sending the request
     * @param {string} threadId 
     * @param {string} [lastMessageId] 
     * @param {string} [lastEntryId] 
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @throws {RequiredError}
     * @memberof ThreadsApiInterface
     */
    streamThreadRequestOpts(requestParameters: StreamThreadRequest): Promise<runtime.RequestOpts>;

    /**
     * SSE endpoint for streaming thread messages.  Opens a server-sent event stream for the given thread. Optionally replays missed entries if last_message_id and last_entry_id are provided.
     * @summary Stream Thread Handler
     * @param {string} threadId 
     * @param {string} [lastMessageId] 
     * @param {string} [lastEntryId] 
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ThreadsApiInterface
     */
    streamThreadRaw(requestParameters: StreamThreadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * SSE endpoint for streaming thread messages.  Opens a server-sent event stream for the given thread. Optionally replays missed entries if last_message_id and last_entry_id are provided.
     * Stream Thread Handler
     */
    streamThread(requestParameters: StreamThreadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Creates request options for updateThread without sending the request
     * @param {string} threadId 
     * @param {UpdateThreadRequest} updateThreadRequest 
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @throws {RequiredError}
     * @memberof ThreadsApiInterface
     */
    updateThreadRequestOpts(requestParameters: UpdateThreadOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Update a thread\'s title and/or parent_thread_id.
     * @summary Update Thread Handler
     * @param {string} threadId 
     * @param {UpdateThreadRequest} updateThreadRequest 
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ThreadsApiInterface
     */
    updateThreadRaw(requestParameters: UpdateThreadOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ThreadResponse>>;

    /**
     * Update a thread\'s title and/or parent_thread_id.
     * Update Thread Handler
     */
    updateThread(requestParameters: UpdateThreadOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ThreadResponse>;

}

/**
 * 
 */
export class ThreadsApi extends runtime.BaseAPI implements ThreadsApiInterface {

    /**
     * Creates request options for createThread without sending the request
     */
    async createThreadRequestOpts(requestParameters: CreateThreadOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createThreadRequest'] == null) {
            throw new runtime.RequiredError(
                'createThreadRequest',
                'Required parameter "createThreadRequest" was null or undefined when calling createThread().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/threads`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateThreadRequestToJSON(requestParameters['createThreadRequest']),
        };
    }

    /**
     * Create a new thread.  If parent_path_part_id is omitted, the thread is created under the user\'s /users/{user_id}/threads/ folder (auto-provisioned if needed).
     * Create Thread Handler
     */
    async createThreadRaw(requestParameters: CreateThreadOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ThreadResponse>> {
        const requestOptions = await this.createThreadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ThreadResponseFromJSON(jsonValue));
    }

    /**
     * Create a new thread.  If parent_path_part_id is omitted, the thread is created under the user\'s /users/{user_id}/threads/ folder (auto-provisioned if needed).
     * Create Thread Handler
     */
    async createThread(requestParameters: CreateThreadOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ThreadResponse> {
        const response = await this.createThreadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteThread without sending the request
     */
    async deleteThreadRequestOpts(requestParameters: DeleteThreadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling deleteThread().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/threads/{thread_id}`;
        urlPath = urlPath.replace(`{${"thread_id"}}`, encodeURIComponent(String(requestParameters['threadId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete a thread.  Authorization: only conversation threads belonging to the current user (under /users/{user_id}/threads/) can be deleted. Asset threads (attached to documents/sections) are never deletable via this endpoint.
     * Delete Thread Handler
     */
    async deleteThreadRaw(requestParameters: DeleteThreadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteThreadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a thread.  Authorization: only conversation threads belonging to the current user (under /users/{user_id}/threads/) can be deleted. Asset threads (attached to documents/sections) are never deletable via this endpoint.
     * Delete Thread Handler
     */
    async deleteThread(requestParameters: DeleteThreadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteThreadRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getThread without sending the request
     */
    async getThreadRequestOpts(requestParameters: GetThreadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling getThread().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/threads/{thread_id}`;
        urlPath = urlPath.replace(`{${"thread_id"}}`, encodeURIComponent(String(requestParameters['threadId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a thread by its thread ID.
     * Get Thread Handler
     */
    async getThreadRaw(requestParameters: GetThreadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ThreadResponse>> {
        const requestOptions = await this.getThreadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ThreadResponseFromJSON(jsonValue));
    }

    /**
     * Get a thread by its thread ID.
     * Get Thread Handler
     */
    async getThread(requestParameters: GetThreadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ThreadResponse> {
        const response = await this.getThreadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listThreads without sending the request
     */
    async listThreadsRequestOpts(requestParameters: ListThreadsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['parentPathPartId'] != null) {
            queryParameters['parent_path_part_id'] = requestParameters['parentPathPartId'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/threads`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List threads under a parent path_part.  When parent_path_part_id is omitted, lists the authenticated user\'s conversation threads from /users/{user_id}/threads/.
     * List Threads Handler
     */
    async listThreadsRaw(requestParameters: ListThreadsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedResponseThreadResponse>> {
        const requestOptions = await this.listThreadsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedResponseThreadResponseFromJSON(jsonValue));
    }

    /**
     * List threads under a parent path_part.  When parent_path_part_id is omitted, lists the authenticated user\'s conversation threads from /users/{user_id}/threads/.
     * List Threads Handler
     */
    async listThreads(requestParameters: ListThreadsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedResponseThreadResponse> {
        const response = await this.listThreadsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sendUserMessage without sending the request
     */
    async sendUserMessageRequestOpts(requestParameters: SendUserMessageRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling sendUserMessage().'
            );
        }

        if (requestParameters['userMessageRequest'] == null) {
            throw new runtime.RequiredError(
                'userMessageRequest',
                'Required parameter "userMessageRequest" was null or undefined when calling sendUserMessage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/threads/{thread_id}/user_message`;
        urlPath = urlPath.replace(`{${"thread_id"}}`, encodeURIComponent(String(requestParameters['threadId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserMessageRequestToJSON(requestParameters['userMessageRequest']),
        };
    }

    /**
     * Send a user message and trigger agent generation. Returns immediately with a workflow_id.  Connect to GET /{thread_id}/stream (SSE) before or after calling this endpoint to receive the streamed output.
     * Send User Message Handler
     */
    async sendUserMessageRaw(requestParameters: SendUserMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<UserMessageResponse>> {
        const requestOptions = await this.sendUserMessageRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => UserMessageResponseFromJSON(jsonValue));
    }

    /**
     * Send a user message and trigger agent generation. Returns immediately with a workflow_id.  Connect to GET /{thread_id}/stream (SSE) before or after calling this endpoint to receive the streamed output.
     * Send User Message Handler
     */
    async sendUserMessage(requestParameters: SendUserMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<UserMessageResponse> {
        const response = await this.sendUserMessageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for streamThread without sending the request
     */
    async streamThreadRequestOpts(requestParameters: StreamThreadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling streamThread().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['lastMessageId'] != null) {
            queryParameters['last_message_id'] = requestParameters['lastMessageId'];
        }

        if (requestParameters['lastEntryId'] != null) {
            queryParameters['last_entry_id'] = requestParameters['lastEntryId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/threads/{thread_id}/stream`;
        urlPath = urlPath.replace(`{${"thread_id"}}`, encodeURIComponent(String(requestParameters['threadId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * SSE endpoint for streaming thread messages.  Opens a server-sent event stream for the given thread. Optionally replays missed entries if last_message_id and last_entry_id are provided.
     * Stream Thread Handler
     */
    async streamThreadRaw(requestParameters: StreamThreadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.streamThreadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * SSE endpoint for streaming thread messages.  Opens a server-sent event stream for the given thread. Optionally replays missed entries if last_message_id and last_entry_id are provided.
     * Stream Thread Handler
     */
    async streamThread(requestParameters: StreamThreadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.streamThreadRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for updateThread without sending the request
     */
    async updateThreadRequestOpts(requestParameters: UpdateThreadOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling updateThread().'
            );
        }

        if (requestParameters['updateThreadRequest'] == null) {
            throw new runtime.RequiredError(
                'updateThreadRequest',
                'Required parameter "updateThreadRequest" was null or undefined when calling updateThread().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/threads/{thread_id}`;
        urlPath = urlPath.replace(`{${"thread_id"}}`, encodeURIComponent(String(requestParameters['threadId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateThreadRequestToJSON(requestParameters['updateThreadRequest']),
        };
    }

    /**
     * Update a thread\'s title and/or parent_thread_id.
     * Update Thread Handler
     */
    async updateThreadRaw(requestParameters: UpdateThreadOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ThreadResponse>> {
        const requestOptions = await this.updateThreadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ThreadResponseFromJSON(jsonValue));
    }

    /**
     * Update a thread\'s title and/or parent_thread_id.
     * Update Thread Handler
     */
    async updateThread(requestParameters: UpdateThreadOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ThreadResponse> {
        const response = await this.updateThreadRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
