/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Stack API
 * Knowledge Stack backend API for authentication and knowledge management
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateThreadMessageRequest,
  HTTPValidationError,
  PaginatedResponseThreadMessageResponse,
  ThreadMessageResponse,
} from '../models/index';
import {
    CreateThreadMessageRequestFromJSON,
    CreateThreadMessageRequestToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    PaginatedResponseThreadMessageResponseFromJSON,
    PaginatedResponseThreadMessageResponseToJSON,
    ThreadMessageResponseFromJSON,
    ThreadMessageResponseToJSON,
} from '../models/index';

export interface CreateThreadMessageOperationRequest {
    threadId: string;
    createThreadMessageRequest: CreateThreadMessageRequest;
    authorization?: string | null;
    ksUat?: string | null;
}

export interface GetThreadMessageRequest {
    threadId: string;
    messageId: string;
    withDetails?: boolean;
    authorization?: string | null;
    ksUat?: string | null;
}

export interface ListThreadMessagesRequest {
    threadId: string;
    before?: Date | null;
    withDetails?: boolean;
    limit?: number;
    offset?: number;
    authorization?: string | null;
    ksUat?: string | null;
}

/**
 * ThreadMessagesApi - interface
 * 
 * @export
 * @interface ThreadMessagesApiInterface
 */
export interface ThreadMessagesApiInterface {
    /**
     * Creates request options for createThreadMessage without sending the request
     * @param {string} threadId 
     * @param {CreateThreadMessageRequest} createThreadMessageRequest 
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @throws {RequiredError}
     * @memberof ThreadMessagesApiInterface
     */
    createThreadMessageRequestOpts(requestParameters: CreateThreadMessageOperationRequest): Promise<runtime.RequestOpts>;

    /**
     * Create a new message in a thread.
     * @summary Create Thread Message Handler
     * @param {string} threadId 
     * @param {CreateThreadMessageRequest} createThreadMessageRequest 
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ThreadMessagesApiInterface
     */
    createThreadMessageRaw(requestParameters: CreateThreadMessageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ThreadMessageResponse>>;

    /**
     * Create a new message in a thread.
     * Create Thread Message Handler
     */
    createThreadMessage(requestParameters: CreateThreadMessageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ThreadMessageResponse>;

    /**
     * Creates request options for getThreadMessage without sending the request
     * @param {string} threadId 
     * @param {string} messageId 
     * @param {boolean} [withDetails] Include execution steps in response (default true)
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @throws {RequiredError}
     * @memberof ThreadMessagesApiInterface
     */
    getThreadMessageRequestOpts(requestParameters: GetThreadMessageRequest): Promise<runtime.RequestOpts>;

    /**
     * Get a specific message by its ID.  Use `with_details=false` to exclude execution step data and reduce payload size.
     * @summary Get Thread Message Handler
     * @param {string} threadId 
     * @param {string} messageId 
     * @param {boolean} [withDetails] Include execution steps in response (default true)
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ThreadMessagesApiInterface
     */
    getThreadMessageRaw(requestParameters: GetThreadMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ThreadMessageResponse>>;

    /**
     * Get a specific message by its ID.  Use `with_details=false` to exclude execution step data and reduce payload size.
     * Get Thread Message Handler
     */
    getThreadMessage(requestParameters: GetThreadMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ThreadMessageResponse>;

    /**
     * Creates request options for listThreadMessages without sending the request
     * @param {string} threadId 
     * @param {Date} [before] Cursor for keyset pagination: only return messages with created_at &lt; this value
     * @param {boolean} [withDetails] Include execution steps in response (default true)
     * @param {number} [limit] Number of items per page
     * @param {number} [offset] Number of items to skip
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @throws {RequiredError}
     * @memberof ThreadMessagesApiInterface
     */
    listThreadMessagesRequestOpts(requestParameters: ListThreadMessagesRequest): Promise<runtime.RequestOpts>;

    /**
     * List messages in a thread, ordered by created_at descending.  Supports cursor-based pagination via `before` parameter and standard offset-based pagination via `limit`/`offset`.  Use `with_details=false` to exclude execution step data and reduce payload size.
     * @summary List Thread Messages Handler
     * @param {string} threadId 
     * @param {Date} [before] Cursor for keyset pagination: only return messages with created_at &lt; this value
     * @param {boolean} [withDetails] Include execution steps in response (default true)
     * @param {number} [limit] Number of items per page
     * @param {number} [offset] Number of items to skip
     * @param {string} [authorization] 
     * @param {string} [ksUat] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ThreadMessagesApiInterface
     */
    listThreadMessagesRaw(requestParameters: ListThreadMessagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedResponseThreadMessageResponse>>;

    /**
     * List messages in a thread, ordered by created_at descending.  Supports cursor-based pagination via `before` parameter and standard offset-based pagination via `limit`/`offset`.  Use `with_details=false` to exclude execution step data and reduce payload size.
     * List Thread Messages Handler
     */
    listThreadMessages(requestParameters: ListThreadMessagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedResponseThreadMessageResponse>;

}

/**
 * 
 */
export class ThreadMessagesApi extends runtime.BaseAPI implements ThreadMessagesApiInterface {

    /**
     * Creates request options for createThreadMessage without sending the request
     */
    async createThreadMessageRequestOpts(requestParameters: CreateThreadMessageOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling createThreadMessage().'
            );
        }

        if (requestParameters['createThreadMessageRequest'] == null) {
            throw new runtime.RequiredError(
                'createThreadMessageRequest',
                'Required parameter "createThreadMessageRequest" was null or undefined when calling createThreadMessage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/threads/{thread_id}/messages`;
        urlPath = urlPath.replace(`{${"thread_id"}}`, encodeURIComponent(String(requestParameters['threadId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateThreadMessageRequestToJSON(requestParameters['createThreadMessageRequest']),
        };
    }

    /**
     * Create a new message in a thread.
     * Create Thread Message Handler
     */
    async createThreadMessageRaw(requestParameters: CreateThreadMessageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ThreadMessageResponse>> {
        const requestOptions = await this.createThreadMessageRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ThreadMessageResponseFromJSON(jsonValue));
    }

    /**
     * Create a new message in a thread.
     * Create Thread Message Handler
     */
    async createThreadMessage(requestParameters: CreateThreadMessageOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ThreadMessageResponse> {
        const response = await this.createThreadMessageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getThreadMessage without sending the request
     */
    async getThreadMessageRequestOpts(requestParameters: GetThreadMessageRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling getThreadMessage().'
            );
        }

        if (requestParameters['messageId'] == null) {
            throw new runtime.RequiredError(
                'messageId',
                'Required parameter "messageId" was null or undefined when calling getThreadMessage().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['withDetails'] != null) {
            queryParameters['with_details'] = requestParameters['withDetails'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/threads/{thread_id}/messages/{message_id}`;
        urlPath = urlPath.replace(`{${"thread_id"}}`, encodeURIComponent(String(requestParameters['threadId'])));
        urlPath = urlPath.replace(`{${"message_id"}}`, encodeURIComponent(String(requestParameters['messageId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get a specific message by its ID.  Use `with_details=false` to exclude execution step data and reduce payload size.
     * Get Thread Message Handler
     */
    async getThreadMessageRaw(requestParameters: GetThreadMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ThreadMessageResponse>> {
        const requestOptions = await this.getThreadMessageRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ThreadMessageResponseFromJSON(jsonValue));
    }

    /**
     * Get a specific message by its ID.  Use `with_details=false` to exclude execution step data and reduce payload size.
     * Get Thread Message Handler
     */
    async getThreadMessage(requestParameters: GetThreadMessageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ThreadMessageResponse> {
        const response = await this.getThreadMessageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for listThreadMessages without sending the request
     */
    async listThreadMessagesRequestOpts(requestParameters: ListThreadMessagesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['threadId'] == null) {
            throw new runtime.RequiredError(
                'threadId',
                'Required parameter "threadId" was null or undefined when calling listThreadMessages().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['before'] != null) {
            queryParameters['before'] = (requestParameters['before'] as any).toISOString();
        }

        if (requestParameters['withDetails'] != null) {
            queryParameters['with_details'] = requestParameters['withDetails'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }


        let urlPath = `/v1/threads/{thread_id}/messages`;
        urlPath = urlPath.replace(`{${"thread_id"}}`, encodeURIComponent(String(requestParameters['threadId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List messages in a thread, ordered by created_at descending.  Supports cursor-based pagination via `before` parameter and standard offset-based pagination via `limit`/`offset`.  Use `with_details=false` to exclude execution step data and reduce payload size.
     * List Thread Messages Handler
     */
    async listThreadMessagesRaw(requestParameters: ListThreadMessagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PaginatedResponseThreadMessageResponse>> {
        const requestOptions = await this.listThreadMessagesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PaginatedResponseThreadMessageResponseFromJSON(jsonValue));
    }

    /**
     * List messages in a thread, ordered by created_at descending.  Supports cursor-based pagination via `before` parameter and standard offset-based pagination via `limit`/`offset`.  Use `with_details=false` to exclude execution step data and reduce payload size.
     * List Thread Messages Handler
     */
    async listThreadMessages(requestParameters: ListThreadMessagesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PaginatedResponseThreadMessageResponse> {
        const response = await this.listThreadMessagesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
