/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Stack API
 * Knowledge Stack backend API for authentication and knowledge management
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Explicit acceptance of the egress disclaimer (must be true).
 * @export
 * @interface AcceptDisclaimerRequest
 */
export interface AcceptDisclaimerRequest {
    /**
     * 
     * @type {boolean}
     * @memberof AcceptDisclaimerRequest
     */
    accepted: boolean;
}
export const AcceptDisclaimerRequestPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}


/**
 * Check if a given object implements the AcceptDisclaimerRequest interface.
 */
export function instanceOfAcceptDisclaimerRequest(value: object): value is AcceptDisclaimerRequest {
    if (!('accepted' in value) || value['accepted'] === undefined) return false;
    return true;
}

export function AcceptDisclaimerRequestFromJSON(json: any): AcceptDisclaimerRequest {
    return AcceptDisclaimerRequestFromJSONTyped(json, false);
}

export function AcceptDisclaimerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AcceptDisclaimerRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'accepted': json['accepted'],
    };
}

export function AcceptDisclaimerRequestToJSON(json: any): AcceptDisclaimerRequest {
    return AcceptDisclaimerRequestToJSONTyped(json, false);
}

export function AcceptDisclaimerRequestToJSONTyped(value?: AcceptDisclaimerRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accepted': value['accepted'],
    };
}

