/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Stack API
 * Knowledge Stack backend API for authentication and knowledge management
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An outbound request the caller (or agent) wants executed.
 * @export
 * @interface ApiConnectionRequestRequest
 */
export interface ApiConnectionRequestRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiConnectionRequestRequest
     */
    method: string;
    /**
     * 
     * @type {string}
     * @memberof ApiConnectionRequestRequest
     */
    path?: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ApiConnectionRequestRequest
     */
    query?: { [key: string]: string; } | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ApiConnectionRequestRequest
     */
    headers?: { [key: string]: string; } | null;
    /**
     * 
     * @type {any}
     * @memberof ApiConnectionRequestRequest
     */
    body?: any | null;
}
export const ApiConnectionRequestRequestPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
    method: {
        maxLength: 16,
    },
    path: {
        maxLength: 4096,
    },
}


/**
 * Check if a given object implements the ApiConnectionRequestRequest interface.
 */
export function instanceOfApiConnectionRequestRequest(value: object): value is ApiConnectionRequestRequest {
    if (!('method' in value) || value['method'] === undefined) return false;
    return true;
}

export function ApiConnectionRequestRequestFromJSON(json: any): ApiConnectionRequestRequest {
    return ApiConnectionRequestRequestFromJSONTyped(json, false);
}

export function ApiConnectionRequestRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiConnectionRequestRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'method': json['method'],
        'path': json['path'] == null ? undefined : json['path'],
        'query': json['query'] == null ? undefined : json['query'],
        'headers': json['headers'] == null ? undefined : json['headers'],
        'body': json['body'] == null ? undefined : json['body'],
    };
}

export function ApiConnectionRequestRequestToJSON(json: any): ApiConnectionRequestRequest {
    return ApiConnectionRequestRequestToJSONTyped(json, false);
}

export function ApiConnectionRequestRequestToJSONTyped(value?: ApiConnectionRequestRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'method': value['method'],
        'path': value['path'],
        'query': value['query'],
        'headers': value['headers'],
        'body': value['body'],
    };
}

