/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Stack API
 * Knowledge Stack backend API for authentication and knowledge management
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CellChangeType = {
    Added: 'added',
    Removed: 'removed',
    Modified: 'modified'
} as const;
export type CellChangeType = typeof CellChangeType[keyof typeof CellChangeType];


export function instanceOfCellChangeType(value: any): boolean {
    for (const key in CellChangeType) {
        if (Object.prototype.hasOwnProperty.call(CellChangeType, key)) {
            if (CellChangeType[key as keyof typeof CellChangeType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CellChangeTypeFromJSON(json: any): CellChangeType {
    return CellChangeTypeFromJSONTyped(json, false);
}

export function CellChangeTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CellChangeType {
    return json as CellChangeType;
}

export function CellChangeTypeToJSON(value?: CellChangeType | null): any {
    return value as any;
}

export function CellChangeTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): CellChangeType {
    return value as CellChangeType;
}

