/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Stack API
 * Knowledge Stack backend API for authentication and knowledge management
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Sort options for the folder-contents listing.
 * 
 * Superset of the base :class:`PathOrder` columns plus ``STATUS``
 * (``approval_state``). Kept separate from ``PathOrder`` so the extra columns
 * do not leak onto ``/folders`` or ``/path-parts``, and only apply at depth 1.
 * @export
 */
export const ContentsSortOrder = {
    Logical: 'LOGICAL',
    Name: 'NAME',
    UpdatedAt: 'UPDATED_AT',
    CreatedAt: 'CREATED_AT',
    Status: 'STATUS',
    Owner: 'OWNER',
    Tags: 'TAGS'
} as const;
export type ContentsSortOrder = typeof ContentsSortOrder[keyof typeof ContentsSortOrder];


export function instanceOfContentsSortOrder(value: any): boolean {
    for (const key in ContentsSortOrder) {
        if (Object.prototype.hasOwnProperty.call(ContentsSortOrder, key)) {
            if (ContentsSortOrder[key as keyof typeof ContentsSortOrder] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ContentsSortOrderFromJSON(json: any): ContentsSortOrder {
    return ContentsSortOrderFromJSONTyped(json, false);
}

export function ContentsSortOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentsSortOrder {
    return json as ContentsSortOrder;
}

export function ContentsSortOrderToJSON(value?: ContentsSortOrder | null): any {
    return value as any;
}

export function ContentsSortOrderToJSONTyped(value: any, ignoreDiscriminator: boolean): ContentsSortOrder {
    return value as ContentsSortOrder;
}

