/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Stack API
 * Knowledge Stack backend API for authentication and knowledge management
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for POST /v1/agent/extract.
 * @export
 * @interface ExtractRequest
 */
export interface ExtractRequest {
    /**
     * User prompt passed directly to the agent
     * @type {string}
     * @memberof ExtractRequest
     */
    prompt: string;
    /**
     * PathPart ID of a KS document whose content is a JSON schema.
     * @type {string}
     * @memberof ExtractRequest
     */
    schemaPathPartId?: string | null;
    /**
     * JSON schema provided inline as a dict. Mutually exclusive with schema_path_part_id; exactly one is required.
     * @type {{ [key: string]: any; }}
     * @memberof ExtractRequest
     */
    outputSchema?: { [key: string]: any; } | null;
}
export const ExtractRequestPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}


/**
 * Check if a given object implements the ExtractRequest interface.
 */
export function instanceOfExtractRequest(value: object): value is ExtractRequest {
    if (!('prompt' in value) || value['prompt'] === undefined) return false;
    return true;
}

export function ExtractRequestFromJSON(json: any): ExtractRequest {
    return ExtractRequestFromJSONTyped(json, false);
}

export function ExtractRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExtractRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'prompt': json['prompt'],
        'schemaPathPartId': json['schema_path_part_id'] == null ? undefined : json['schema_path_part_id'],
        'outputSchema': json['output_schema'] == null ? undefined : json['output_schema'],
    };
}

export function ExtractRequestToJSON(json: any): ExtractRequest {
    return ExtractRequestToJSONTyped(json, false);
}

export function ExtractRequestToJSONTyped(value?: ExtractRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'prompt': value['prompt'],
        'schema_path_part_id': value['schemaPathPartId'],
        'output_schema': value['outputSchema'],
    };
}

