/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Stack API
 * Knowledge Stack backend API for authentication and knowledge management
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SupportedLanguage } from './SupportedLanguage';
import {
    SupportedLanguageFromJSON,
    SupportedLanguageFromJSONTyped,
    SupportedLanguageToJSON,
    SupportedLanguageToJSONTyped,
} from './SupportedLanguage';

/**
 * 
 * @export
 * @interface FeaturesResponse
 */
export interface FeaturesResponse {
    /**
     * 
     * @type {boolean}
     * @memberof FeaturesResponse
     */
    googleLoginEnabled: boolean;
    /**
     * 
     * @type {SupportedLanguage}
     * @memberof FeaturesResponse
     */
    defaultFrontendLanguage: SupportedLanguage;
}


export const FeaturesResponsePropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}


/**
 * Check if a given object implements the FeaturesResponse interface.
 */
export function instanceOfFeaturesResponse(value: object): value is FeaturesResponse {
    if (!('googleLoginEnabled' in value) || value['googleLoginEnabled'] === undefined) return false;
    if (!('defaultFrontendLanguage' in value) || value['defaultFrontendLanguage'] === undefined) return false;
    return true;
}

export function FeaturesResponseFromJSON(json: any): FeaturesResponse {
    return FeaturesResponseFromJSONTyped(json, false);
}

export function FeaturesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeaturesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'googleLoginEnabled': json['google_login_enabled'],
        'defaultFrontendLanguage': SupportedLanguageFromJSON(json['default_frontend_language']),
    };
}

export function FeaturesResponseToJSON(json: any): FeaturesResponse {
    return FeaturesResponseToJSONTyped(json, false);
}

export function FeaturesResponseToJSONTyped(value?: FeaturesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'google_login_enabled': value['googleLoginEnabled'],
        'default_frontend_language': SupportedLanguageToJSON(value['defaultFrontendLanguage']),
    };
}

