/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Stack API
 * Knowledge Stack backend API for authentication and knowledge management
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Sortable fields for invite listings.
 * @export
 */
export const InviteOrder = {
    CreatedAt: 'CREATED_AT',
    ExpiresAt: 'EXPIRES_AT'
} as const;
export type InviteOrder = typeof InviteOrder[keyof typeof InviteOrder];


export function instanceOfInviteOrder(value: any): boolean {
    for (const key in InviteOrder) {
        if (Object.prototype.hasOwnProperty.call(InviteOrder, key)) {
            if (InviteOrder[key as keyof typeof InviteOrder] === value) {
                return true;
            }
        }
    }
    return false;
}

export function InviteOrderFromJSON(json: any): InviteOrder {
    return InviteOrderFromJSONTyped(json, false);
}

export function InviteOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): InviteOrder {
    return json as InviteOrder;
}

export function InviteOrderToJSON(value?: InviteOrder | null): any {
    return value as any;
}

export function InviteOrderToJSONTyped(value: any, ignoreDiscriminator: boolean): InviteOrder {
    return value as InviteOrder;
}

