/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Stack API
 * Knowledge Stack backend API for authentication and knowledge management
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LineageEdgeResponse } from './LineageEdgeResponse';
import {
    LineageEdgeResponseFromJSON,
    LineageEdgeResponseFromJSONTyped,
    LineageEdgeResponseToJSON,
    LineageEdgeResponseToJSONTyped,
} from './LineageEdgeResponse';
import type { LineageNodeResponse } from './LineageNodeResponse';
import {
    LineageNodeResponseFromJSON,
    LineageNodeResponseFromJSONTyped,
    LineageNodeResponseToJSON,
    LineageNodeResponseToJSONTyped,
} from './LineageNodeResponse';

/**
 * Complete lineage graph with nodes and edges.
 * @export
 * @interface LineageGraphResponse
 */
export interface LineageGraphResponse {
    /**
     * Chunk nodes in the graph
     * @type {Array<LineageNodeResponse>}
     * @memberof LineageGraphResponse
     */
    nodes: Array<LineageNodeResponse>;
    /**
     * Lineage edges in the graph
     * @type {Array<LineageEdgeResponse>}
     * @memberof LineageGraphResponse
     */
    edges: Array<LineageEdgeResponse>;
}
export const LineageGraphResponsePropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}


/**
 * Check if a given object implements the LineageGraphResponse interface.
 */
export function instanceOfLineageGraphResponse(value: object): value is LineageGraphResponse {
    if (!('nodes' in value) || value['nodes'] === undefined) return false;
    if (!('edges' in value) || value['edges'] === undefined) return false;
    return true;
}

export function LineageGraphResponseFromJSON(json: any): LineageGraphResponse {
    return LineageGraphResponseFromJSONTyped(json, false);
}

export function LineageGraphResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LineageGraphResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'nodes': ((json['nodes'] as Array<any>).map(LineageNodeResponseFromJSON)),
        'edges': ((json['edges'] as Array<any>).map(LineageEdgeResponseFromJSON)),
    };
}

export function LineageGraphResponseToJSON(json: any): LineageGraphResponse {
    return LineageGraphResponseToJSONTyped(json, false);
}

export function LineageGraphResponseToJSONTyped(value?: LineageGraphResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nodes': ((value['nodes'] as Array<any>).map(LineageNodeResponseToJSON)),
        'edges': ((value['edges'] as Array<any>).map(LineageEdgeResponseToJSON)),
    };
}

