/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Stack API
 * Knowledge Stack backend API for authentication and knowledge management
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Owner scope for a memory document.
 * 
 * Lowercase values match the request-schema Literals so no mapping layer is
 * needed. ``user`` resolves to /users/{user_id}; ``workflow`` to the workflow
 * definition's path_part. (Tenant scope is deferred.)
 * @export
 */
export const MemoryScope = {
    User: 'user',
    Workflow: 'workflow'
} as const;
export type MemoryScope = typeof MemoryScope[keyof typeof MemoryScope];


export function instanceOfMemoryScope(value: any): boolean {
    for (const key in MemoryScope) {
        if (Object.prototype.hasOwnProperty.call(MemoryScope, key)) {
            if (MemoryScope[key as keyof typeof MemoryScope] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MemoryScopeFromJSON(json: any): MemoryScope {
    return MemoryScopeFromJSONTyped(json, false);
}

export function MemoryScopeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemoryScope {
    return json as MemoryScope;
}

export function MemoryScopeToJSON(value?: MemoryScope | null): any {
    return value as any;
}

export function MemoryScopeToJSONTyped(value: any, ignoreDiscriminator: boolean): MemoryScope {
    return value as MemoryScope;
}

