/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Stack API
 * Knowledge Stack backend API for authentication and knowledge management
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GroupPermissionResponse } from './GroupPermissionResponse';
import {
    GroupPermissionResponseFromJSON,
    GroupPermissionResponseFromJSONTyped,
    GroupPermissionResponseToJSON,
    GroupPermissionResponseToJSONTyped,
} from './GroupPermissionResponse';

/**
 * 
 * @export
 * @interface PaginatedResponseGroupPermissionResponse
 */
export interface PaginatedResponseGroupPermissionResponse {
    /**
     * List of items
     * @type {Array<GroupPermissionResponse>}
     * @memberof PaginatedResponseGroupPermissionResponse
     */
    items: Array<GroupPermissionResponse>;
    /**
     * Total number of items
     * @type {number}
     * @memberof PaginatedResponseGroupPermissionResponse
     */
    total: number;
    /**
     * Number of items per page
     * @type {number}
     * @memberof PaginatedResponseGroupPermissionResponse
     */
    limit: number;
    /**
     * Number of items to skip
     * @type {number}
     * @memberof PaginatedResponseGroupPermissionResponse
     */
    offset: number;
}
export const PaginatedResponseGroupPermissionResponsePropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
    total: {
        minimum: 0,
        exclusiveMinimum: false,
    },
    limit: {
        minimum: 1,
        exclusiveMinimum: false,
    },
    offset: {
        minimum: 0,
        exclusiveMinimum: false,
    },
}


/**
 * Check if a given object implements the PaginatedResponseGroupPermissionResponse interface.
 */
export function instanceOfPaginatedResponseGroupPermissionResponse(value: object): value is PaginatedResponseGroupPermissionResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    return true;
}

export function PaginatedResponseGroupPermissionResponseFromJSON(json: any): PaginatedResponseGroupPermissionResponse {
    return PaginatedResponseGroupPermissionResponseFromJSONTyped(json, false);
}

export function PaginatedResponseGroupPermissionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedResponseGroupPermissionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(GroupPermissionResponseFromJSON)),
        'total': json['total'],
        'limit': json['limit'],
        'offset': json['offset'],
    };
}

export function PaginatedResponseGroupPermissionResponseToJSON(json: any): PaginatedResponseGroupPermissionResponse {
    return PaginatedResponseGroupPermissionResponseToJSONTyped(json, false);
}

export function PaginatedResponseGroupPermissionResponseToJSONTyped(value?: PaginatedResponseGroupPermissionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(GroupPermissionResponseToJSON)),
        'total': value['total'],
        'limit': value['limit'],
        'offset': value['offset'],
    };
}

