/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Stack API
 * Knowledge Stack backend API for authentication and knowledge management
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Type of path part in the filesystem.
 * @export
 */
export const PartType = {
    Folder: 'FOLDER',
    Document: 'DOCUMENT',
    DocumentVersion: 'DOCUMENT_VERSION',
    Section: 'SECTION',
    Chunk: 'CHUNK',
    Thread: 'THREAD',
    ThreadMessage: 'THREAD_MESSAGE',
    WorkflowDefinition: 'WORKFLOW_DEFINITION',
    WorkflowRun: 'WORKFLOW_RUN',
    DataSource: 'DATA_SOURCE',
    DataSourceTable: 'DATA_SOURCE_TABLE'
} as const;
export type PartType = typeof PartType[keyof typeof PartType];


export function instanceOfPartType(value: any): boolean {
    for (const key in PartType) {
        if (Object.prototype.hasOwnProperty.call(PartType, key)) {
            if (PartType[key as keyof typeof PartType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PartTypeFromJSON(json: any): PartType {
    return PartTypeFromJSONTyped(json, false);
}

export function PartTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartType {
    return json as PartType;
}

export function PartTypeToJSON(value?: PartType | null): any {
    return value as any;
}

export function PartTypeToJSONTyped(value: any, ignoreDiscriminator: boolean): PartType {
    return value as PartType;
}

