/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Stack API
 * Knowledge Stack backend API for authentication and knowledge management
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Tenant subscription lifecycle state, mirrors Stripe subscription status.
 * 
 * Must include every status value Stripe can send, otherwise webhook
 * handling silently drops updates. See
 * https://stripe.com/docs/api/subscriptions/object#subscription_object-status.
 * @export
 */
export const SubscriptionStatus = {
    Active: 'ACTIVE',
    Trialing: 'TRIALING',
    PastDue: 'PAST_DUE',
    Canceled: 'CANCELED',
    Incomplete: 'INCOMPLETE',
    IncompleteExpired: 'INCOMPLETE_EXPIRED',
    Unpaid: 'UNPAID',
    Paused: 'PAUSED'
} as const;
export type SubscriptionStatus = typeof SubscriptionStatus[keyof typeof SubscriptionStatus];


export function instanceOfSubscriptionStatus(value: any): boolean {
    for (const key in SubscriptionStatus) {
        if (Object.prototype.hasOwnProperty.call(SubscriptionStatus, key)) {
            if (SubscriptionStatus[key as keyof typeof SubscriptionStatus] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SubscriptionStatusFromJSON(json: any): SubscriptionStatus {
    return SubscriptionStatusFromJSONTyped(json, false);
}

export function SubscriptionStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubscriptionStatus {
    return json as SubscriptionStatus;
}

export function SubscriptionStatusToJSON(value?: SubscriptionStatus | null): any {
    return value as any;
}

export function SubscriptionStatusToJSONTyped(value: any, ignoreDiscriminator: boolean): SubscriptionStatus {
    return value as SubscriptionStatus;
}

