/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Stack API
 * Knowledge Stack backend API for authentication and knowledge management
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const SupportedLanguage = {
    En: 'en',
    Zh: 'zh'
} as const;
export type SupportedLanguage = typeof SupportedLanguage[keyof typeof SupportedLanguage];


export function instanceOfSupportedLanguage(value: any): boolean {
    for (const key in SupportedLanguage) {
        if (Object.prototype.hasOwnProperty.call(SupportedLanguage, key)) {
            if (SupportedLanguage[key as keyof typeof SupportedLanguage] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SupportedLanguageFromJSON(json: any): SupportedLanguage {
    return SupportedLanguageFromJSONTyped(json, false);
}

export function SupportedLanguageFromJSONTyped(json: any, ignoreDiscriminator: boolean): SupportedLanguage {
    return json as SupportedLanguage;
}

export function SupportedLanguageToJSON(value?: SupportedLanguage | null): any {
    return value as any;
}

export function SupportedLanguageToJSONTyped(value: any, ignoreDiscriminator: boolean): SupportedLanguage {
    return value as SupportedLanguage;
}

