/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Stack API
 * Knowledge Stack backend API for authentication and knowledge management
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TenantBrandingResponse } from './TenantBrandingResponse';
import {
    TenantBrandingResponseFromJSON,
    TenantBrandingResponseFromJSONTyped,
    TenantBrandingResponseToJSON,
    TenantBrandingResponseToJSONTyped,
} from './TenantBrandingResponse';
import type { TenantSettingsResponse } from './TenantSettingsResponse';
import {
    TenantSettingsResponseFromJSON,
    TenantSettingsResponseFromJSONTyped,
    TenantSettingsResponseToJSON,
    TenantSettingsResponseToJSONTyped,
} from './TenantSettingsResponse';

/**
 * Tenant response model.
 * @export
 * @interface TenantResponse
 */
export interface TenantResponse {
    /**
     * Tenant ID
     * @type {string}
     * @memberof TenantResponse
     */
    id: string;
    /**
     * Tenant name
     * @type {string}
     * @memberof TenantResponse
     */
    name: string;
    /**
     * External IdP configuration
     * @type {{ [key: string]: any; }}
     * @memberof TenantResponse
     */
    idpConfig?: { [key: string]: any; } | null;
    /**
     * 
     * @type {TenantSettingsResponse}
     * @memberof TenantResponse
     */
    settings: TenantSettingsResponse;
    /**
     * 
     * @type {TenantBrandingResponse}
     * @memberof TenantResponse
     */
    branding?: TenantBrandingResponse;
}
export const TenantResponsePropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}


/**
 * Check if a given object implements the TenantResponse interface.
 */
export function instanceOfTenantResponse(value: object): value is TenantResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('settings' in value) || value['settings'] === undefined) return false;
    return true;
}

export function TenantResponseFromJSON(json: any): TenantResponse {
    return TenantResponseFromJSONTyped(json, false);
}

export function TenantResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'idpConfig': json['idp_config'] == null ? undefined : json['idp_config'],
        'settings': TenantSettingsResponseFromJSON(json['settings']),
        'branding': json['branding'] == null ? undefined : TenantBrandingResponseFromJSON(json['branding']),
    };
}

export function TenantResponseToJSON(json: any): TenantResponse {
    return TenantResponseToJSONTyped(json, false);
}

export function TenantResponseToJSONTyped(value?: TenantResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'idp_config': value['idpConfig'],
        'settings': TenantSettingsResponseToJSON(value['settings']),
        'branding': TenantBrandingResponseToJSON(value['branding']),
    };
}

