/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Stack API
 * Knowledge Stack backend API for authentication and knowledge management
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Resolved branding with presigned URLs instead of internal S3 URIs.
 * @export
 * @interface TenantBrandingResponse
 */
export interface TenantBrandingResponse {
    /**
     * Custom brand name for logo
     * @type {string}
     * @memberof TenantBrandingResponse
     */
    brandName?: string | null;
    /**
     * Primary brand hex color
     * @type {string}
     * @memberof TenantBrandingResponse
     */
    brandColor?: string | null;
    /**
     * Presigned URL for primary logo
     * @type {string}
     * @memberof TenantBrandingResponse
     */
    logoUrl?: string | null;
    /**
     * Presigned URL for dark-mode logo
     * @type {string}
     * @memberof TenantBrandingResponse
     */
    logoDarkUrl?: string | null;
    /**
     * Presigned URL for favicon
     * @type {string}
     * @memberof TenantBrandingResponse
     */
    faviconUrl?: string | null;
    /**
     * Custom CSS variable overrides
     * @type {{ [key: string]: string; }}
     * @memberof TenantBrandingResponse
     */
    themeOverrides?: { [key: string]: string; } | null;
}
export const TenantBrandingResponsePropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}


/**
 * Check if a given object implements the TenantBrandingResponse interface.
 */
export function instanceOfTenantBrandingResponse(value: object): value is TenantBrandingResponse {
    return true;
}

export function TenantBrandingResponseFromJSON(json: any): TenantBrandingResponse {
    return TenantBrandingResponseFromJSONTyped(json, false);
}

export function TenantBrandingResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TenantBrandingResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'brandName': json['brand_name'] == null ? undefined : json['brand_name'],
        'brandColor': json['brand_color'] == null ? undefined : json['brand_color'],
        'logoUrl': json['logo_url'] == null ? undefined : json['logo_url'],
        'logoDarkUrl': json['logo_dark_url'] == null ? undefined : json['logo_dark_url'],
        'faviconUrl': json['favicon_url'] == null ? undefined : json['favicon_url'],
        'themeOverrides': json['theme_overrides'] == null ? undefined : json['theme_overrides'],
    };
}

export function TenantBrandingResponseToJSON(json: any): TenantBrandingResponse {
    return TenantBrandingResponseToJSONTyped(json, false);
}

export function TenantBrandingResponseToJSONTyped(value?: TenantBrandingResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'brand_name': value['brandName'],
        'brand_color': value['brandColor'],
        'logo_url': value['logoUrl'],
        'logo_dark_url': value['logoDarkUrl'],
        'favicon_url': value['faviconUrl'],
        'theme_overrides': value['themeOverrides'],
    };
}

