/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Stack API
 * Knowledge Stack backend API for authentication and knowledge management
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserInfo } from './UserInfo';
import {
    UserInfoFromJSON,
    UserInfoFromJSONTyped,
    UserInfoToJSON,
    UserInfoToJSONTyped,
} from './UserInfo';

/**
 * 
 * @export
 * @interface ThreadResponse
 */
export interface ThreadResponse {
    /**
     * Thread ID
     * @type {string}
     * @memberof ThreadResponse
     */
    id: string;
    /**
     * PathPart ID
     * @type {string}
     * @memberof ThreadResponse
     */
    pathPartId: string;
    /**
     * Thread title
     * @type {string}
     * @memberof ThreadResponse
     */
    title: string;
    /**
     * Parent Thread ID (for subthreads)
     * @type {string}
     * @memberof ThreadResponse
     */
    parentThreadId?: string | null;
    /**
     * Full materialized path from root
     * @type {string}
     * @memberof ThreadResponse
     */
    materializedPath: string;
    /**
     * Tenant ID
     * @type {string}
     * @memberof ThreadResponse
     */
    tenantId: string;
    /**
     * Current owner (creator) of the thread, or null if unowned.
     * @type {UserInfo}
     * @memberof ThreadResponse
     */
    owner?: UserInfo | null;
    /**
     * Creation timestamp
     * @type {Date}
     * @memberof ThreadResponse
     */
    createdAt: Date;
    /**
     * Last update timestamp
     * @type {Date}
     * @memberof ThreadResponse
     */
    updatedAt: Date;
}
export const ThreadResponsePropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}


/**
 * Check if a given object implements the ThreadResponse interface.
 */
export function instanceOfThreadResponse(value: object): value is ThreadResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('pathPartId' in value) || value['pathPartId'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('materializedPath' in value) || value['materializedPath'] === undefined) return false;
    if (!('tenantId' in value) || value['tenantId'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('updatedAt' in value) || value['updatedAt'] === undefined) return false;
    return true;
}

export function ThreadResponseFromJSON(json: any): ThreadResponse {
    return ThreadResponseFromJSONTyped(json, false);
}

export function ThreadResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThreadResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'pathPartId': json['path_part_id'],
        'title': json['title'],
        'parentThreadId': json['parent_thread_id'] == null ? undefined : json['parent_thread_id'],
        'materializedPath': json['materialized_path'],
        'tenantId': json['tenant_id'],
        'owner': json['owner'] == null ? undefined : UserInfoFromJSON(json['owner']),
        'createdAt': (new Date(json['created_at'])),
        'updatedAt': (new Date(json['updated_at'])),
    };
}

export function ThreadResponseToJSON(json: any): ThreadResponse {
    return ThreadResponseToJSONTyped(json, false);
}

export function ThreadResponseToJSONTyped(value?: ThreadResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'path_part_id': value['pathPartId'],
        'title': value['title'],
        'parent_thread_id': value['parentThreadId'],
        'materialized_path': value['materializedPath'],
        'tenant_id': value['tenantId'],
        'owner': UserInfoToJSON(value['owner']),
        'created_at': value['createdAt'].toISOString(),
        'updated_at': value['updatedAt'].toISOString(),
    };
}

