/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Stack API
 * Knowledge Stack backend API for authentication and knowledge management
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StepInput } from './StepInput';
import {
    StepInputFromJSON,
    StepInputFromJSONTyped,
    StepInputToJSON,
    StepInputToJSONTyped,
} from './StepInput';

/**
 * 
 * @export
 * @interface ThreadMessageDetailsInput
 */
export interface ThreadMessageDetailsInput {
    /**
     * 
     * @type {Array<StepInput>}
     * @memberof ThreadMessageDetailsInput
     */
    steps?: Array<StepInput>;
}
export const ThreadMessageDetailsInputPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}


/**
 * Check if a given object implements the ThreadMessageDetailsInput interface.
 */
export function instanceOfThreadMessageDetailsInput(value: object): value is ThreadMessageDetailsInput {
    return true;
}

export function ThreadMessageDetailsInputFromJSON(json: any): ThreadMessageDetailsInput {
    return ThreadMessageDetailsInputFromJSONTyped(json, false);
}

export function ThreadMessageDetailsInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ThreadMessageDetailsInput {
    if (json == null) {
        return json;
    }
    return {
        
        'steps': json['steps'] == null ? undefined : ((json['steps'] as Array<any>).map(StepInputFromJSON)),
    };
}

export function ThreadMessageDetailsInputToJSON(json: any): ThreadMessageDetailsInput {
    return ThreadMessageDetailsInputToJSONTyped(json, false);
}

export function ThreadMessageDetailsInputToJSONTyped(value?: ThreadMessageDetailsInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'steps': value['steps'] == null ? undefined : ((value['steps'] as Array<any>).map(StepInputToJSON)),
    };
}

