/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Stack API
 * Knowledge Stack backend API for authentication and knowledge management
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Rename and/or move a connector (PATCH). Both fields optional.
 * 
 * A body with both ``None`` is rejected as a no-op 400. ``name`` renames
 * the connector path_part; ``parent_path_part_id`` moves it under a new
 * FOLDER (the move cascades ``materialized_path`` to the modeled-table
 * children). Connection credentials and engine are not editable here.
 * @export
 * @interface UpdateDataSourceRequest
 */
export interface UpdateDataSourceRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateDataSourceRequest
     */
    name?: string | null;
    /**
     * New parent FOLDER path_part to move the connector under.
     * @type {string}
     * @memberof UpdateDataSourceRequest
     */
    parentPathPartId?: string | null;
}
export const UpdateDataSourceRequestPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
    name: {
        maxLength: 255,
        minLength: 1,
    },
}


/**
 * Check if a given object implements the UpdateDataSourceRequest interface.
 */
export function instanceOfUpdateDataSourceRequest(value: object): value is UpdateDataSourceRequest {
    return true;
}

export function UpdateDataSourceRequestFromJSON(json: any): UpdateDataSourceRequest {
    return UpdateDataSourceRequestFromJSONTyped(json, false);
}

export function UpdateDataSourceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateDataSourceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'parentPathPartId': json['parent_path_part_id'] == null ? undefined : json['parent_path_part_id'],
    };
}

export function UpdateDataSourceRequestToJSON(json: any): UpdateDataSourceRequest {
    return UpdateDataSourceRequestToJSONTyped(json, false);
}

export function UpdateDataSourceRequestToJSONTyped(value?: UpdateDataSourceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'parent_path_part_id': value['parentPathPartId'],
    };
}

