/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Stack API
 * Knowledge Stack backend API for authentication and knowledge management
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ChunkMetadata } from './ChunkMetadata';
import {
    ChunkMetadataFromJSON,
    ChunkMetadataFromJSONTyped,
    ChunkMetadataToJSON,
    ChunkMetadataToJSONTyped,
} from './ChunkMetadata';

/**
 * Request to update chunk metadata and/or move the chunk.
 * @export
 * @interface UpdateChunkMetadataRequest
 */
export interface UpdateChunkMetadataRequest {
    /**
     * Metadata to merge into existing chunk_metadata (optional)
     * @type {ChunkMetadata}
     * @memberof UpdateChunkMetadataRequest
     */
    chunkMetadata?: ChunkMetadata | null;
    /**
     * Reparent to this PathPart ID (must be DOCUMENT_VERSION or SECTION in the same document version)
     * @type {string}
     * @memberof UpdateChunkMetadataRequest
     */
    parentPathPartId?: string | null;
    /**
     * Move after this sibling PathPart ID (within new or current parent)
     * @type {string}
     * @memberof UpdateChunkMetadataRequest
     */
    prevSiblingPathId?: string | null;
    /**
     * Set to true to move to head of sibling list
     * @type {boolean}
     * @memberof UpdateChunkMetadataRequest
     */
    moveToHead?: boolean;
}
export const UpdateChunkMetadataRequestPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}


/**
 * Check if a given object implements the UpdateChunkMetadataRequest interface.
 */
export function instanceOfUpdateChunkMetadataRequest(value: object): value is UpdateChunkMetadataRequest {
    return true;
}

export function UpdateChunkMetadataRequestFromJSON(json: any): UpdateChunkMetadataRequest {
    return UpdateChunkMetadataRequestFromJSONTyped(json, false);
}

export function UpdateChunkMetadataRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateChunkMetadataRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'chunkMetadata': json['chunk_metadata'] == null ? undefined : ChunkMetadataFromJSON(json['chunk_metadata']),
        'parentPathPartId': json['parent_path_part_id'] == null ? undefined : json['parent_path_part_id'],
        'prevSiblingPathId': json['prev_sibling_path_id'] == null ? undefined : json['prev_sibling_path_id'],
        'moveToHead': json['move_to_head'] == null ? undefined : json['move_to_head'],
    };
}

export function UpdateChunkMetadataRequestToJSON(json: any): UpdateChunkMetadataRequest {
    return UpdateChunkMetadataRequestToJSONTyped(json, false);
}

export function UpdateChunkMetadataRequestToJSONTyped(value?: UpdateChunkMetadataRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'chunk_metadata': ChunkMetadataToJSON(value['chunkMetadata']),
        'parent_path_part_id': value['parentPathPartId'],
        'prev_sibling_path_id': value['prevSiblingPathId'],
        'move_to_head': value['moveToHead'],
    };
}

