/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Stack API
 * Knowledge Stack backend API for authentication and knowledge management
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IdpType } from './IdpType';
import {
    IdpTypeFromJSON,
    IdpTypeFromJSONTyped,
    IdpTypeToJSON,
    IdpTypeToJSONTyped,
} from './IdpType';
import type { TenantUserRole } from './TenantUserRole';
import {
    TenantUserRoleFromJSON,
    TenantUserRoleFromJSONTyped,
    TenantUserRoleToJSON,
    TenantUserRoleToJSONTyped,
} from './TenantUserRole';

/**
 * 
 * @export
 * @interface UserResponse
 */
export interface UserResponse {
    /**
     * User ID
     * @type {string}
     * @memberof UserResponse
     */
    id: string;
    /**
     * Email address of the user
     * @type {string}
     * @memberof UserResponse
     */
    email: string | null;
    /**
     * First name of the user
     * @type {string}
     * @memberof UserResponse
     */
    firstName: string | null;
    /**
     * Last name of the user
     * @type {string}
     * @memberof UserResponse
     */
    lastName: string | null;
    /**
     * 
     * @type {IdpType}
     * @memberof UserResponse
     */
    idpType: IdpType;
    /**
     * Current tenant ID the user is logged into
     * @type {string}
     * @memberof UserResponse
     */
    currentTenantId: string;
    /**
     * 
     * @type {TenantUserRole}
     * @memberof UserResponse
     */
    currentTenantRole: TenantUserRole;
    /**
     * Default tenant ID the user shall be logged into
     * @type {string}
     * @memberof UserResponse
     */
    defaultTenantId: string;
}


export const UserResponsePropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}


/**
 * Check if a given object implements the UserResponse interface.
 */
export function instanceOfUserResponse(value: object): value is UserResponse {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('idpType' in value) || value['idpType'] === undefined) return false;
    if (!('currentTenantId' in value) || value['currentTenantId'] === undefined) return false;
    if (!('currentTenantRole' in value) || value['currentTenantRole'] === undefined) return false;
    if (!('defaultTenantId' in value) || value['defaultTenantId'] === undefined) return false;
    return true;
}

export function UserResponseFromJSON(json: any): UserResponse {
    return UserResponseFromJSONTyped(json, false);
}

export function UserResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'email': json['email'],
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'idpType': IdpTypeFromJSON(json['idp_type']),
        'currentTenantId': json['current_tenant_id'],
        'currentTenantRole': TenantUserRoleFromJSON(json['current_tenant_role']),
        'defaultTenantId': json['default_tenant_id'],
    };
}

export function UserResponseToJSON(json: any): UserResponse {
    return UserResponseToJSONTyped(json, false);
}

export function UserResponseToJSONTyped(value?: UserResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'email': value['email'],
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'idp_type': IdpTypeToJSON(value['idpType']),
        'current_tenant_id': value['currentTenantId'],
        'current_tenant_role': TenantUserRoleToJSON(value['currentTenantRole']),
        'default_tenant_id': value['defaultTenantId'],
    };
}

