/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Stack API
 * Knowledge Stack backend API for authentication and knowledge management
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Adoption proxies for a workflow-runs summary.
 * 
 * These are deliberately labelled "adoption", not "value" — they measure
 * how much the system is used, not the business value it produced (which is
 * not derivable from any column we store).
 * @export
 * @interface WorkflowAdoptionStats
 */
export interface WorkflowAdoptionStats {
    /**
     * Runs created in the window.
     * @type {number}
     * @memberof WorkflowAdoptionStats
     */
    runs: number;
    /**
     * Currently-active workflow definitions in scope (not windowed).
     * @type {number}
     * @memberof WorkflowAdoptionStats
     */
    activeDefinitions: number;
    /**
     * Distinct run owners in the window.
     * @type {number}
     * @memberof WorkflowAdoptionStats
     */
    distinctTriggerers: number;
}
export const WorkflowAdoptionStatsPropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}


/**
 * Check if a given object implements the WorkflowAdoptionStats interface.
 */
export function instanceOfWorkflowAdoptionStats(value: object): value is WorkflowAdoptionStats {
    if (!('runs' in value) || value['runs'] === undefined) return false;
    if (!('activeDefinitions' in value) || value['activeDefinitions'] === undefined) return false;
    if (!('distinctTriggerers' in value) || value['distinctTriggerers'] === undefined) return false;
    return true;
}

export function WorkflowAdoptionStatsFromJSON(json: any): WorkflowAdoptionStats {
    return WorkflowAdoptionStatsFromJSONTyped(json, false);
}

export function WorkflowAdoptionStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowAdoptionStats {
    if (json == null) {
        return json;
    }
    return {
        
        'runs': json['runs'],
        'activeDefinitions': json['active_definitions'],
        'distinctTriggerers': json['distinct_triggerers'],
    };
}

export function WorkflowAdoptionStatsToJSON(json: any): WorkflowAdoptionStats {
    return WorkflowAdoptionStatsToJSONTyped(json, false);
}

export function WorkflowAdoptionStatsToJSONTyped(value?: WorkflowAdoptionStats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'runs': value['runs'],
        'active_definitions': value['activeDefinitions'],
        'distinct_triggerers': value['distinctTriggerers'],
    };
}

