/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Stack API
 * Knowledge Stack backend API for authentication and knowledge management
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response for generic workflow cancellation.
 * @export
 * @interface WorkflowCancelResponse
 */
export interface WorkflowCancelResponse {
    /**
     * 
     * @type {string}
     * @memberof WorkflowCancelResponse
     */
    workflowId: string;
    /**
     * 
     * @type {string}
     * @memberof WorkflowCancelResponse
     */
    message: string;
}
export const WorkflowCancelResponsePropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}


/**
 * Check if a given object implements the WorkflowCancelResponse interface.
 */
export function instanceOfWorkflowCancelResponse(value: object): value is WorkflowCancelResponse {
    if (!('workflowId' in value) || value['workflowId'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function WorkflowCancelResponseFromJSON(json: any): WorkflowCancelResponse {
    return WorkflowCancelResponseFromJSONTyped(json, false);
}

export function WorkflowCancelResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowCancelResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'workflowId': json['workflow_id'],
        'message': json['message'],
    };
}

export function WorkflowCancelResponseToJSON(json: any): WorkflowCancelResponse {
    return WorkflowCancelResponseToJSONTyped(json, false);
}

export function WorkflowCancelResponseToJSONTyped(value?: WorkflowCancelResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'workflow_id': value['workflowId'],
        'message': value['message'],
    };
}

