/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Stack API
 * Knowledge Stack backend API for authentication and knowledge management
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response from the runner callback endpoint.
 * @export
 * @interface WorkflowCallbackResponse
 */
export interface WorkflowCallbackResponse {
    /**
     * 
     * @type {string}
     * @memberof WorkflowCallbackResponse
     */
    status: string;
}
export const WorkflowCallbackResponsePropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}


/**
 * Check if a given object implements the WorkflowCallbackResponse interface.
 */
export function instanceOfWorkflowCallbackResponse(value: object): value is WorkflowCallbackResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function WorkflowCallbackResponseFromJSON(json: any): WorkflowCallbackResponse {
    return WorkflowCallbackResponseFromJSONTyped(json, false);
}

export function WorkflowCallbackResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowCallbackResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function WorkflowCallbackResponseToJSON(json: any): WorkflowCallbackResponse {
    return WorkflowCallbackResponseToJSONTyped(json, false);
}

export function WorkflowCallbackResponseToJSONTyped(value?: WorkflowCallbackResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

