/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Stack API
 * Knowledge Stack backend API for authentication and knowledge management
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Execution lifecycle of a workflow run.
 * 
 * Two-step flow lifecycle:
 * 
 * * ``PENDING`` — entry state when the create call carries uploads.
 *   Inputs are being ingested by Temporal; the run cannot be started
 *   yet. The ingestion-completion hook auto-flips the run to
 *   ``NOT_STARTED`` once every input under ``inputs/`` reaches
 *   ``pipeline_state.status == COMPLETED``.
 * * ``NOT_STARTED`` — entry state when the create call has no
 *   uploads (KB references only), OR the post-ingestion landing
 *   pad. The user can Start the run from here.
 * * ``IN_PROGRESS`` — set by ``POST /v1/workflow-runs/{id}/start``,
 *   which builds the snapshot and dispatches the Temporal workflow.
 * * ``COMPLETED`` / ``FAILED`` — terminal; ``completed_at`` is set.
 * @export
 */
export const WorkflowExecutionState = {
    Pending: 'PENDING',
    NotStarted: 'NOT_STARTED',
    InProgress: 'IN_PROGRESS',
    Completed: 'COMPLETED',
    Failed: 'FAILED'
} as const;
export type WorkflowExecutionState = typeof WorkflowExecutionState[keyof typeof WorkflowExecutionState];


export function instanceOfWorkflowExecutionState(value: any): boolean {
    for (const key in WorkflowExecutionState) {
        if (Object.prototype.hasOwnProperty.call(WorkflowExecutionState, key)) {
            if (WorkflowExecutionState[key as keyof typeof WorkflowExecutionState] === value) {
                return true;
            }
        }
    }
    return false;
}

export function WorkflowExecutionStateFromJSON(json: any): WorkflowExecutionState {
    return WorkflowExecutionStateFromJSONTyped(json, false);
}

export function WorkflowExecutionStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowExecutionState {
    return json as WorkflowExecutionState;
}

export function WorkflowExecutionStateToJSON(value?: WorkflowExecutionState | null): any {
    return value as any;
}

export function WorkflowExecutionStateToJSONTyped(value: any, ignoreDiscriminator: boolean): WorkflowExecutionState {
    return value as WorkflowExecutionState;
}

