/* tslint:disable */
/* eslint-disable */
/**
 * Knowledge Stack API
 * Knowledge Stack backend API for authentication and knowledge management
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { WorkflowAdoptionStats } from './WorkflowAdoptionStats';
import {
    WorkflowAdoptionStatsFromJSON,
    WorkflowAdoptionStatsFromJSONTyped,
    WorkflowAdoptionStatsToJSON,
    WorkflowAdoptionStatsToJSONTyped,
} from './WorkflowAdoptionStats';

/**
 * Aggregate workflow-runs health over a window, permission-scoped.
 * 
 * Read-gated like the run list: the numbers cover only runs under workflows
 * the caller can read (OWNER/ADMIN ⇒ tenant-wide). All windowed metrics
 * filter runs by ``created_at`` in ``[window_start, window_end]``; the
 * approval backlog and ``active_definitions`` are point-in-time (not
 * windowed). ``failure_rate`` and the duration percentiles are ``None`` when
 * their denominator set is empty.
 * @export
 * @interface WorkflowRunSummaryResponse
 */
export interface WorkflowRunSummaryResponse {
    /**
     * 
     * @type {Date}
     * @memberof WorkflowRunSummaryResponse
     */
    windowStart: Date;
    /**
     * 
     * @type {Date}
     * @memberof WorkflowRunSummaryResponse
     */
    windowEnd: Date | null;
    /**
     * Runs created in the window.
     * @type {number}
     * @memberof WorkflowRunSummaryResponse
     */
    total: number;
    /**
     * Run count per execution_state (all states present).
     * @type {{ [key: string]: number; }}
     * @memberof WorkflowRunSummaryResponse
     */
    countsByState: { [key: string]: number; };
    /**
     * FAILED / (COMPLETED + FAILED); null when no terminal runs.
     * @type {number}
     * @memberof WorkflowRunSummaryResponse
     */
    failureRate: number | null;
    /**
     * Median run duration over terminal runs; null when none.
     * @type {number}
     * @memberof WorkflowRunSummaryResponse
     */
    durationP50Seconds: number | null;
    /**
     * p95 run duration over terminal runs; null when none.
     * @type {number}
     * @memberof WorkflowRunSummaryResponse
     */
    durationP95Seconds: number | null;
    /**
     * Runs currently awaiting approval (point-in-time).
     * @type {number}
     * @memberof WorkflowRunSummaryResponse
     */
    pendingApprovalCount: number;
    /**
     * Age of the oldest pending-approval request; null when none.
     * @type {number}
     * @memberof WorkflowRunSummaryResponse
     */
    oldestPendingAgeSeconds: number | null;
    /**
     * 
     * @type {WorkflowAdoptionStats}
     * @memberof WorkflowRunSummaryResponse
     */
    adoption: WorkflowAdoptionStats;
}
export const WorkflowRunSummaryResponsePropertyValidationAttributesMap: {
    [property: string]: {
        maxLength?: number,
        minLength?: number,
        pattern?: string,
        maximum?: number,
        exclusiveMaximum?: boolean,
        minimum?: number,
        exclusiveMinimum?: boolean,
        multipleOf?: number,
        maxItems?: number,
        minItems?: number,
        uniqueItems?: boolean
    }
} = {
}


/**
 * Check if a given object implements the WorkflowRunSummaryResponse interface.
 */
export function instanceOfWorkflowRunSummaryResponse(value: object): value is WorkflowRunSummaryResponse {
    if (!('windowStart' in value) || value['windowStart'] === undefined) return false;
    if (!('windowEnd' in value) || value['windowEnd'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('countsByState' in value) || value['countsByState'] === undefined) return false;
    if (!('failureRate' in value) || value['failureRate'] === undefined) return false;
    if (!('durationP50Seconds' in value) || value['durationP50Seconds'] === undefined) return false;
    if (!('durationP95Seconds' in value) || value['durationP95Seconds'] === undefined) return false;
    if (!('pendingApprovalCount' in value) || value['pendingApprovalCount'] === undefined) return false;
    if (!('oldestPendingAgeSeconds' in value) || value['oldestPendingAgeSeconds'] === undefined) return false;
    if (!('adoption' in value) || value['adoption'] === undefined) return false;
    return true;
}

export function WorkflowRunSummaryResponseFromJSON(json: any): WorkflowRunSummaryResponse {
    return WorkflowRunSummaryResponseFromJSONTyped(json, false);
}

export function WorkflowRunSummaryResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WorkflowRunSummaryResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'windowStart': (new Date(json['window_start'])),
        'windowEnd': (json['window_end'] == null ? null : new Date(json['window_end'])),
        'total': json['total'],
        'countsByState': json['counts_by_state'],
        'failureRate': json['failure_rate'],
        'durationP50Seconds': json['duration_p50_seconds'],
        'durationP95Seconds': json['duration_p95_seconds'],
        'pendingApprovalCount': json['pending_approval_count'],
        'oldestPendingAgeSeconds': json['oldest_pending_age_seconds'],
        'adoption': WorkflowAdoptionStatsFromJSON(json['adoption']),
    };
}

export function WorkflowRunSummaryResponseToJSON(json: any): WorkflowRunSummaryResponse {
    return WorkflowRunSummaryResponseToJSONTyped(json, false);
}

export function WorkflowRunSummaryResponseToJSONTyped(value?: WorkflowRunSummaryResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'window_start': value['windowStart'].toISOString(),
        'window_end': value['windowEnd'] == null ? value['windowEnd'] : value['windowEnd'].toISOString(),
        'total': value['total'],
        'counts_by_state': value['countsByState'],
        'failure_rate': value['failureRate'],
        'duration_p50_seconds': value['durationP50Seconds'],
        'duration_p95_seconds': value['durationP95Seconds'],
        'pending_approval_count': value['pendingApprovalCount'],
        'oldest_pending_age_seconds': value['oldestPendingAgeSeconds'],
        'adoption': WorkflowAdoptionStatsToJSON(value['adoption']),
    };
}

